### ISSUE TITLE
Block Lighting bugs in flat neighboring chunks

### ISSUE THREAD

**Issue by Zailer43** [Spottedleaf/Starlight#1]
### Expected Behavior
When I place the light source everything lights up properly

### Actual Behavior
When I place the light source, everything doesn't light up properly

### Reproduction Steps

1. Build something like this (the wall or floor must be completely flat (or at least the part where light reaches) and be on the edge of the other chunk, but the bug will not occur)
![2020-11-25_21 38 59](https://user-images.githubusercontent.com/63565983/100294819-a832c000-2f66-11eb-937f-cdc2d395912b.png)

2. Place a light source at least 1 block away from the wall or floor
![2020-11-25_21 30 50](https://user-images.githubusercontent.com/63565983/100295001-3018ca00-2f67-11eb-8ed4-e458845b9d2d.png)

### Mod Version
- starlight-0.0.1-SNAPSHOT

### Additional screenshots
![2020-11-24_19 41 24](https://user-images.githubusercontent.com/63565983/100295342-2479d300-2f68-11eb-9ea5-0657b014f9c1.png)

5681942750785458012
`/execute in minecraft:overworld run tp @s 44.39 37.57 -304.14 -112.63 -8.26`
![2020-11-25_21 52 41](https://user-images.githubusercontent.com/63565983/100295512-90f4d200-2f68-11eb-8798-173e8e3aad93.png)

5681942750785458012
`/execute in minecraft:overworld run tp @s -955.04 25.00 88.25 68.13 9.18`
![2020-11-25_21 56 00](https://user-images.githubusercontent.com/63565983/100295740-16788200-2f69-11eb-8c6b-f1e875df9cf1.png)

**Comment by Spottedleaf** [comment]
I don't know what's causing that from the looks of it, but I suspect it has something to do with the initialisation of block light nibbles

**Comment by Spottedleaf** [comment]
https://www.youtube.com/watch?v=-9x1bXbH9Sw

**Comment by Spottedleaf** [comment]
Actually, this looks like an issue where I'm not queueing neighbour chunks to be re-rendered.

**Comment by Spottedleaf** [comment]
I have this fixed locally, I'll push when I've refactored the skylight nibble management.
