### ISSUE TITLE
intended use clarification

### ISSUE THREAD

**Issue by end-user** [Spottedleaf/Starlight#101]
Can you clarify (esp on the readme): is starlight primarily intended for use on a server or client?  Are there client-side-only benefits to be had?  I assume light rendering is done client-side, but I'm not really sure.

**Comment by electronicboy** [comment]
starlight is a lighting *engine* replacement, it's the mechanism that calculates the light levels, etc; Both the client and the server has this logic, and both of them recalculate the light level here and there; starlight has nothing to do with rendering, that's still all on the rendering mechanism, etc

the server is primarily what deals with lighting, but, the client also updates lighting on its own, so, there are benefits to having starlight on both of them
