### ISSUE TITLE
Lighting Flickers At Chunk Borders When Placing/Breaking Light Sources

### ISSUE THREAD

**Issue by AViewFromTheTop** [Spottedleaf/Starlight#105]
The title is self-explanatory- I was placing and breaking Glowstone, and the light from it seemed to flicker quickly at chunk borders each time I placed/broke it. You might need a high refresh rate to be able to see it, because it is quite fast- I doubt anyone playing with 60FPS or lower is going to see this. (If it helps, my refresh rate is about 165, and I was using Sodium to get better performance in-game.)
 Version is 1.18.

**Comment by Taiyou06** [comment]
try without sodium

**Comment by Puremin0rez** [comment]
Are you able to reproduce this without Sodium?

My best guess is that this is from the threaded chunk updates in 1.18.

Make sure `Always Defer Chunk Updates` isn't checked in Sodium, and if the issue exists within Vanilla too, try setting `Chunk Builder` to something other than `Threaded`. `Fully Blocking` would be the behavior of 1.17 and earlier.

**Comment by AViewFromTheTop** [comment]
I've tried again with no mods aside from Starlight, apparently this only happens with Chunk Builder switched to Semi-Blocking.
I tried in vanilla and got the same result, which is odd, as I've never seen this before, and I've played it unmodded for a while.
The issue is with vanilla, so I'll close this issue now. Thank you for the help!
