### ISSUE TITLE
Account for `getLightEmission(blockState, level, pos)` on Forge

### ISSUE THREAD

**Issue by Matthysse** [Spottedleaf/Starlight#108]
Hello!
The forge version uses the fabric method for light "getLightEmission()" instead of "getLightEmission(blockState, level, pos)"
This causes for example in Supplementaries: lit candles on skulls don't emit light.

**Comment by jpenilla** [comment]
I don't think this is "forge vs fabric methods" as much as it is "vanilla vs forge-added methods"

**Comment by Spottedleaf** [comment]
https://github.com/MehVahdJukaar/Supplementaries/commit/e7963136441d873c401bd08493fc7b30b0561b0f resolves the specific conflict here, but technically I should use the hook anyways.

**Comment by Matthysse** [comment]
Yep the Supplementaries Dev said I should still report the issue as other Devs may use it. Thanks for looking into it !
Any news on Create compatibility ? On 1.18 it still crashes with starlight

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Starlight/commit/36a1c6c4f7231b3294109c4ddf9eb5bb0133eb8c
