### ISSUE TITLE
[Forge][1.18.1] Crash with Create/Flywheel

### ISSUE THREAD

**Issue by dierks-m** [Spottedleaf/Starlight#115]
# Issue Description
On the new version of Create (v0.4b) with Flywheel (v0.5.0a) running on Forge 39.0.9 a moving contraption (e.g. a piston) will cause the game to crash when it tries to move (this is on an existing world). After testing, this will already occur when trying to place down the piston.
[Crash Report Here](https://gist.github.com/wieselkatze/90caf873c914cc0172fa7b2e2474e8ba)
Last part of stack trace:
`Caused by: java.lang.ClassCastException: class com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter cannot be cast to class net.minecraft.world.level.Level (com.jozufozu.flywheel.core.virtual.VirtualEmptyBlockGetter is in module flywheel@1.18-0.5.0a of loader 'TRANSFORMER' @4248b963; net.minecraft.world.level.Level is in module minecraft@1.18.1 of loader 'TRANSFORMER' @4248b963)
	at ca.spottedleaf.starlight.common.light.StarLightInterface.<init>(StarLightInterface.java:62) ~[starlight-1.0.0+forge.4fd2e63.jar%2354!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}`

# Reproduction Steps
Using an instance with those three mods, already trying to place down the piston will crash the game.

**Comment by AeiouEnigma** [comment]
This is fixed for the next release of Starlight, which is being delayed until the next release of Create, as there are issues on both sides that impede compatibility.

In the meantime, you can download my builds of [Create](https://github.com/The-Vowels/Create/releases/tag/amverysmart) and [Starlight](https://github.com/AeiouEnigma/Starlight/releases/tag/create_compatibility) which incorporate these fixes.

**Comment by dierks-m** [comment]
Alright, thanks!
