### ISSUE TITLE
Crash at startup 1.18.1

### ISSUE THREAD

**Issue by agentwolf88** [Spottedleaf/Starlight#117]
[crash-2022-01-09_22.37.58-client.txt](https://github.com/PaperMC/Starlight/files/7836034/crash-2022-01-09_22.37.58-client.txt)

**Comment by Klouver-github** [comment]
do you have mcjty installed?

**Comment by agentwolf88** [comment]
Yes

**Comment by Klouver-github** [comment]
it saids Mcjty not installed and your mod list saids it's not installed

**Comment by Spottedleaf** [comment]
Resolved by https://github.com/PaperMC/Starlight/commit/fef9eb9aef5c1b22c5e35a5766ae27b21902cace, I should have mentioned the fix was to download the mod again (although really I should have just made a new release).
