### ISSUE TITLE
When upgrading from 0.0.1 to 0.0.2, your world is deleted

### ISSUE THREAD

**Issue by QPCrummer** [Spottedleaf/Starlight#12]
When flying over oceans, I have noticed some chunks are randomly lit up. There is no light source and when f3 is pressed, it says that there isn't any block light. I don't know if this is client side or server side.
**Mods on server: Starlight, Tic-Tacs, Lithium, SmoothBoot, BBOR, Carpet, Carpet Extra, Fabric Api, Fast Furnace, Fabric Geyser, Hydrogen, Krypton**

![2020-12-22_14 36 26](https://user-images.githubusercontent.com/66036033/102926795-a96ee400-4463-11eb-9df6-21b2b0d3d995.png)
![2020-12-22_14 36 46](https://user-images.githubusercontent.com/66036033/102926805-ad9b0180-4463-11eb-8ab6-c66576ce5573.png)

**Comment by Spottedleaf** [comment]
Can you reproduce with just starlight? (Note: you'll have to create a new world)

**Comment by QPCrummer** [comment]
This is a brand new world on my server. It seems to be a chunk lighting problem. I only have starlight on it and on the client. 
![f](https://user-images.githubusercontent.com/66036033/102928442-af19f900-4466-11eb-93d9-d2abe6dda403.png)

**Comment by QPCrummer** [comment]
Without the mod installed on client, it is slightly better, but the glitch is still occurring.
![F3](https://user-images.githubusercontent.com/66036033/102928792-5f87fd00-4467-11eb-8314-7ce6f78b6cc7.png)

**Comment by QPCrummer** [comment]
Strangely, without the mod on both the server and client, the problem still occurs. I haven't ever had this happen in vanilla minecraft before (besides in like 1.7).
![strange](https://user-images.githubusercontent.com/66036033/102929249-3e73dc00-4468-11eb-97f0-d01ec0be5445.png)

**Comment by QPCrummer** [comment]
Just in case you need a reference of what mods I have on my client and server. This is without starlight.
![Servermods](https://user-images.githubusercontent.com/66036033/102929484-b17d5280-4468-11eb-8656-759421f47215.JPG)
![mods](https://user-images.githubusercontent.com/66036033/102929487-b17d5280-4468-11eb-9d66-924a2b424f5e.JPG)

**Comment by QPCrummer** [comment]
One other thing that might be helpful. When I swim down to the light, it goes from skylight level 0, straight to skylight level 15.

**Comment by QPCrummer** [comment]
I have just found something huge! All of the caves in my world are lit up! That means no mob spawning! This is a big deal as I run a server with roughly 20-30 people.
![cave](https://user-images.githubusercontent.com/66036033/102933029-6ca8ea00-446f-11eb-804b-a659c6b09aea.png)

**Comment by Spottedleaf** [comment]
If you can provide world seed & coords I can take a look at this when I've time

**Comment by Spottedleaf** [comment]
Also, are you using 0.0.1 or 0.0.2-rc1?

**Comment by QPCrummer** [comment]
The seed is 6449431131609745321
The coords are: -521, 76, 582

**Comment by QPCrummer** [comment]
0.0.1

**Comment by Spottedleaf** [comment]
oh I don't support 0.0.1 anymore, can you produce on 0.0.2-rc1?

**Comment by QPCrummer** [comment]
Let me try

**Comment by QPCrummer** [comment]
It deleted my world. It was also giving "couldn't load chunk ~ ~ ~" errors in the console

**Comment by QPCrummer** [comment]
![snippy](https://user-images.githubusercontent.com/66036033/102933757-daa1e100-4470-11eb-9e71-be45e1e09a1f.JPG)

**Comment by QPCrummer** [comment]
There is no lighting issue, but my entire world is gone. The main problem is fixed, now there is a new one ):

**Comment by Spottedleaf** [comment]
It looks like tictacs is incompatible

**Comment by QPCrummer** [comment]
Until this is fixed, I am using phosphor just to get some extra performance. Hope you can find a solution! Best of luck!

**Comment by Spottedleaf** [comment]
Due to very technical reasons, I literally can do nothing from my end. This is a tictacs issue.
