### ISSUE TITLE
[Fabric 1.18.1] "Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin"

### ISSUE THREAD

**Issue by 0xf0xx0** [Spottedleaf/Starlight#120]
I can't start the client with Starlight enabled. It crashes with the error `Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin`. Full log attached.
[latest.log](https://github.com/PaperMC/Starlight/files/7886107/latest.log)

**Comment by ghost** [comment]
It appears that you're using an outdated version of Starlight (1.0.0-RC3), which was released in July for 1.17. This is unfortunately the newest version available on GitHub releases. The [Modrinth](https://modrinth.com/mod/starlight) page for this mod should have the newest, 1.18 compatible, version based on d0a3220.

**Comment by 0xf0xx0** [comment]
ah yep, youre right, the modrinth one works
