### ISSUE TITLE
(Forge) Incompatible with Flywheel

### ISSUE THREAD

**Issue by BigPhobos** [Spottedleaf/Starlight#121]
https://gist.github.com/LunarPhobos/f01bb2aba63021df9b0f2842faeb6a41

**Comment by AeiouEnigma** [comment]
Update to Starlight 1.0.1

You can find it listed as an alpha release on CurseForge.

**Comment by Jozufozu** [comment]
@Spottedleaf the fix is confirmed to work, 1.0.1 can be bumped to release

**Comment by Spottedleaf** [comment]
Forgot to close this
