### ISSUE TITLE
1.18.1 Forge crash on startup with "square corners font"

### ISSUE THREAD

**Issue by agentwolf88** [Spottedleaf/Starlight#124]
[crash-2022-01-31_22.00.24-client.txt](https://github.com/PaperMC/Starlight/files/7974265/crash-2022-01-31_22.00.24-client.txt)

https://imgur.com/a/WG13wIc

**Comment by Dekamir** [comment]
Not Enough Crashes intercepted your crash, but the client failed to load fonts beforehand. Happens quite often. Try disabling to get the actual crash.
Also disable OptiFine for the time being.

**Comment by agentwolf88** [comment]
[crash-2022-02-07_21.08.54-client.txt](https://github.com/PaperMC/Starlight/files/8018377/crash-2022-02-07_21.08.54-client.txt)

**Comment by Dekamir** [comment]
**[I'm not the mod developer. Take my advices with a grain of salt.]**

It looks like you're running a lot of GUI/HUD mods. 
- FancyMenu cannot be the issue as I'm running it too.
- The One Probe created problems while loading, but I'm running it too as well.

- Looks like the game is crashing while creating the Loading Screen, which means some mods are trying to access the same method, and Starlight may intercept with its rendering methods.
- OdysseyHUD caused an error. Might check that out.
- You're on Mac OS. I don't know if the mod is compatible with that OS.

I'd go with the "disable half of the mods, if it crashes, repeat" method if I were you. Create another instance where you can quickly launch and crash the game. JEI and OptiFine take a lot of time to load, so don't put them and mods dependent on them in your test environment. Focus on mods which modifies GUI and HUD, or have advanced ones themselves.

Oh, and it would be nice to change your client language to English, if you can. My German isn't sufficient enough to read debug texts. _If your client is already in English, force Java to use English (US) Locale._

**Comment by Spottedleaf** [comment]
I don't see Starlight causing this, we don't do anything with the mod loading order, the mod loading screen, or really anything to do with that.
