### ISSUE TITLE
[1.16.5 - Starlight X Create v1.2] Incompatibility with New TARDIS Mod

### ISSUE THREAD

**Issue by Elfinlocks** [Spottedleaf/Starlight#125]
Starlight X Create has a minor incompatibility with [TARDIS mod](https://www.curseforge.com/minecraft/mc-mods/new-tardis-mod) - when using the interior lighting feature, the slider does not adjust the light level, I presume due to the rewrite of the lighting engine.

To reproduce:
1. Install Starlight X Create v1.2 for 1.16.5
2. Install New TARDIS mod v1.5.3 (latest 1.16 release)
3. Place a "broken exterior" block
4. Use clocks (minecraft:clock) on it until it opens
5. Use the command "/tardis setup" to set up the TARDIS. 
6. Access any control panel (on the walls), and select Interior Properties
7. Attempt to change the light level via the slider - will have no effect

Per TARDIS mod team, as their system uses the vanilla light engine, I should report this here.

Thank you!

**Comment by AeiouEnigma** [comment]
There is no Starlight release for 1.16. "Starlight x Create" is a separate project entirely unaffiliated with this one. You should report your issue on their GitHub page.

**Comment by Spottedleaf** [comment]
1.16 is not supported
