### ISSUE TITLE
[1.16.5 - Starlight X Create v1.2] Incompatibility with Miner's Helmet

### ISSUE THREAD

**Issue by Elfinlocks** [Spottedleaf/Starlight#126]
When Starlight X Create v1.2 is installed, the Miner's Helmets from the [mod by the same name](https://www.curseforge.com/minecraft/mc-mods/miners-helmet) do not shed light, when equipped by players or mobs.

![image](https://user-images.githubusercontent.com/43624750/152069526-f87172e1-f10e-4f40-8335-faadad5e2492.png)

To reproduce:
1. Install Starlight X Create v1.2 for Minecraft 1.16
2. Install Miner's Helmet v2.0.1 for Minecraft 1.16
3. Equip a Miner's Helmet, or spawn a Miner's Helmet zombie.
4. Observe that the helmet does not shed light as normal

Thank you!

**Comment by Spottedleaf** [comment]
1.16 is not supported
