### ISSUE TITLE
1.18.1 Forge 39.0.66 - Crashes instantly on launch

### ISSUE THREAD

**Issue by cobaltw** [Spottedleaf/Starlight#128]
Whenever attempting to run this mod (regardless of other mods installed) the game instantly crashes to the launcher. No crash report is generated, and the minecraft window doesn't even appear, it just goes straight back to the launcher after hitting play.

**Comment by cobaltw** [comment]
whoops, this is meant for starlight & create, but there doesn't seem to be a place to submit issues for that. closing, since it's not relevant for this repository

**Comment by AeiouEnigma** [comment]
On 1.18 you don't need any unofficial fork of Starlight. You can download Starlight 1.0.1 off of CurseForge, and it will be fully compatible with any version of Create from 0.4c onward.
