### ISSUE TITLE
World Fails To Load When Using Any Version Of Lithium

### ISSUE THREAD

**Issue by Funtimes909** [Spottedleaf/Starlight#129]
Out of nowhere starlight seems to be compatible with both 0.7.6 and 0.7.7 versions of lithium, what makes it really stand out to me is that I was using these mods together fine until a few days ago when they seemingly out of nowhere didn't work together.
I've tried re-downloading both of these mods and have even tested on both
[latest.log](https://github.com/PaperMC/Starlight/files/8028015/latest.log)

**Comment by theRookieCoder** [comment]
Not sure if this is related but how did you run Hydrogen on 1.18.1? It was only ever updated to 1.17.1 and is now archived

**Comment by theRookieCoder** [comment]
Firstly, I am unable to replicate this with Lithium 0.7.9 and Starlight 1.0.2 on Fabric Loader 0.13.3-1.18.2, this probably means there are other mods causing issues. I have sussed out C2ME, Better FPS Render Distance, and Hydrogen. Speaking of Hydrogen, how did you get it to work on 1.18? The latest version it supported was 1.17.1 and Hydrogen has been archived. Either its these mods or they fixed this incompatibility between Lithium 0.7.7 and 0.7.9

**Comment by Funtimes909** [comment]
> Firstly, I am unable to replicate this with Lithium 0.7.9 and Starlight 1.0.2 on Fabric Loader 0.13.3-1.18.2, this probably means there are other mods causing issues. I have sussed out C2ME, Better FPS Render Distance, and Hydrogen. Speaking of Hydrogen, how did you get it to work on 1.18? The latest version it supported was 1.17.1 and Hydrogen has been archived. Either its these mods or they fixed this incompatibility between Lithium 0.7.7 and 0.7.9

Hi, Thanks for replying, thankfully I sorted out this issue awhile ago now, I can't remember what the issue was anymore haha, I think it was something to do with sodium extra? I really can't remember lol. About hydrogen, I think there is a 1.18 preview of it on the GitHub page however I doubt it will work for 1.18.1 and above due to recent changes Mojang made to which java libraries are included in the base game or something along those lines.

**Comment by theRookieCoder** [comment]
Ah I see. Just a quick reminder that you should close issues after you've fixed them or found out that they're not related to the project
