### ISSUE TITLE
Release as a Spigot plugin

### ISSUE THREAD

**Issue by justadudeongithub** [Spottedleaf/Starlight#130]
I'm don't know much about development, so if my request is stupid forgive me. Since @Spottedleaf is on PaperMC it's kind of a bummer Starlight isn't available as a Spigot plugin. AFAIK Spigot forks are much more popular on servers than Fabric so a plugin would be much more impactful to Minecraft.

**Comment by electronicboy** [comment]
starlight isn't a plugin and requires fairly deep modification of the game which isn't supported in a spigot environment.
starlight already exists inside paper however

**Comment by justadudeongithub** [comment]
Ah, okay. Thank you for clarification and the work you've put in to this.
