### ISSUE TITLE
dedicated server load up frezes

### ISSUE THREAD

**Issue by ZEROX7** [Spottedleaf/Starlight#132]
wehn starlight and quark is installed on a dedicated server the server hangs up on befor world creation and right after mod loading
in hte log the crash does not apear only in the console
![image](https://user-images.githubusercontent.com/12628051/153760377-593fc551-62ac-41e2-8dc9-3cb1bdf17cdc.png)
[latest.log](https://github.com/PaperMC/Starlight/files/8055918/latest.log)

**Comment by WFPhantom** [comment]
It's incompatible with Quark for some reason.

**Comment by WFPhantom** [comment]
u can close this if u update the mods :)
