### ISSUE TITLE
minecraft wont open with starlight x create, java runtime error

### ISSUE THREAD

**Issue by Kylress** [Spottedleaf/Starlight#134]
i had this modpack since create 1.18.1 dropped, downloaded the mod to get a better performance, i know it's probably a incompatibility error since the mod is in development, but wanted to report it anyway

crash report:
[crash.txt](https://github.com/PaperMC/Starlight/files/8061359/crash.txt)

error on launcher:
this crash may be caused by an invalid java runtime configuration

**Comment by electronicboy** [comment]
`starlight-x-create` - that has nothing to do with us

**Comment by AeiouEnigma** [comment]
If you're using the latest version of Create (0.4c or later) just download Starlight 1.0.1 from CurseForge (NOT "Starlight x Create"), and you should have no issues.
