### ISSUE TITLE
[1.18.1] Incompatibility with Immersive Engineering's Manual

### ISSUE THREAD

**Issue by FynnWaelsing** [Spottedleaf/Starlight#135]
Using Starlight together with Immersive Engineering causes the displaying of how complex machines are crafted to be broken in the Engineering Manual. The corresponding issue on their Github can be found here, showing what happens when Starlight is installed: https://github.com/BluSunrize/ImmersiveEngineering/issues/5161.

Starlight version: starlight-1.0.1+forge.36a1c6c
Forge version: 39.0.79

**Comment by malte0811** [comment]
Fixed in IE: BluSunrize/ImmersiveEngineering@4acd027f1826c72e1460671d480087ddfaa5e7a3
