### ISSUE TITLE
[Forge 1.18.1] Client Crash with Create

### ISSUE THREAD

**Issue by AdeptusAutumn** [Spottedleaf/Starlight#136]
[crash-2022-02-20_14.33.16-client.txt](https://github.com/PaperMC/Starlight/files/8104085/crash-2022-02-20_14.33.16-client.txt)

[crash-2022-02-20_14.38.57-client.txt](https://github.com/PaperMC/Starlight/files/8104078/crash-2022-02-20_14.38.57-client.txt)

Mod Version: starlight-1.0.1+forge.36a1c6c

Tried to move a Mechanical Piston construct with another mechanical Piston. Dedicated Server keeps on running, but crashes client on relog as well

**Comment by NBZion** [comment]
Whats your forge version

**Comment by HexedHero** [comment]
> Whats your forge version

Forge: net.minecraftforge:39.0.76
It says in the crash report.

**Comment by NBZion** [comment]
Try updating forge to the latest version

**Comment by JuJuTheWulfPup** [comment]
I'm seeing the same issue
Moving a sticky/non-sticky mechanical piston while pointing downwards causes this issue
Facing any other direction is OK

Forge 39.1.0
Minecraft 1.18.1
mods: Create 0.4d + Starlight 1.0.0+forgeb1f6a10 (disabled everything else while narrowing down the issue)
[crash-2022-05-08_09.18.43-client.txt](https://github.com/PaperMC/Starlight/files/8647139/crash-2022-05-08_09.18.43-client.txt)

**Comment by TheNitroExpress** [comment]
Here with the same issue. Mechanical piston facing down and pulling up causes a crash with starlight

**Comment by JuJuTheWulfPup** [comment]
Just to let others  know in case you didn't think of it yourself, you can still play your modpack if you disable Starlight. That's what I had all my friends do so we can still play. It's not ideal of course, but it's still playable for us.

Starlight is an efficient lighting engine replacement, so it's not really necessary.

**Comment by Dakedres** [comment]
Issue does not occur with [Radon](https://www.curseforge.com/minecraft/mc-mods/radon), so that's another alternative (still at the cost of the performance Starlight brings). Have not checked with Phosphor & Create Refabricated

**Comment by SuperStormer** [comment]
I think this is fixed by https://github.com/Creators-of-Create/Create/pull/3111?

**Comment by Spottedleaf** [comment]
Yeah it looks like they may have created a world with 0 sections by accident which was resolved.
