### ISSUE TITLE
[1.18.1][Forge] General Slight Performance Decrease

### ISSUE THREAD

**Issue by ShibeTemple** [Spottedleaf/Starlight#137]
Versions:
```Minecraft 1.18.1
Forge 39.0.79
Starlight 1.0.1 - starlight-1.0.1+forge.36a1c6c.jar
```

Mod list (±Starlight):
```Catalogue - catalogue-1.6.0-1.18.1.jar
Configured - configured-1.5.3-1.18.1.jar
Controlling - Controlling-forge-1.18.1-9.0+15.jar
FPS Monitor (provides FPS text when not in F3) - FPS-Monitor-1.18-1.0.2.jar
JEI - jei-1.18.1-9.2.1.69.jar
```

There is a noticeable, albeit slight, performance drop when the latest version of Starlight is installed. I understand this mod's goal is to not increase framerate, however, there is a baseline average drop even when chunks are not being rendered in or out. 

I have attached screenshots of some tests I performed. The first set is looking at the same position and standing at the same position after a few minutes of being in the world. 

VANILLA: 

![2022-02-20_11 02 20](https://user-images.githubusercontent.com/6219801/154862740-df9d49e7-11b6-4155-ac80-4fb7d023aa52.png)
![2022-02-20_11 03 26](https://user-images.githubusercontent.com/6219801/154862752-9771954c-b9d4-4271-abe4-4b366db4aace.png)
360 test/viewport movement
![2022-02-20_11 04 49](https://user-images.githubusercontent.com/6219801/154862785-e3c14023-59a0-4d8c-8a56-c4b37177796d.png)

STARLIGHT: 

![2022-02-20_11 19 47](https://user-images.githubusercontent.com/6219801/154862856-be167619-aefb-4d94-9fe4-b5908df6d270.png)
![2022-02-20_11 21 15](https://user-images.githubusercontent.com/6219801/154862872-45cc9cbd-4ac6-480e-b2fa-d006db294291.png)
360 test
![2022-02-20_11 20 14](https://user-images.githubusercontent.com/6219801/154862893-0ed1f680-8575-4d4a-85d5-1bcbe6f15fec.png)

RAM usage is better, however!!! :)

**Comment by Spottedleaf** [comment]
I would need client sparks to identify an issue, given that my local benchmarking doesn't really show anything.
