### ISSUE TITLE
[1.18.1 - Starlight Create version (Has no tracker, reporting here. Don't yell at me.)] Game crashes. No report is made.

### ISSUE THREAD

**Issue by MagmaSlime123** [Spottedleaf/Starlight#138]
Title. Since no crash report is made, I can only give a log file.

[latest.log](https://github.com/PaperMC/Starlight/files/8105564/latest.log)

**Comment by electronicboy** [comment]
This repo is for starlight, not a mod which is an amalgamation of two different mods
Starlight and create apparently works now

**Comment by MagmaSlime123** [comment]
May want to remove the old mod then.

https://www.curseforge.com/minecraft/mc-mods/starlight-x-create

**Comment by electronicboy** [comment]
That mod has nothing to do with us

**Comment by MagmaSlime123** [comment]
Ah, alright. Sorry then.
