### ISSUE TITLE
[fabric 1.18.1] 1.0.1 archived

### ISSUE THREAD

**Issue by itsdinkd** [Spottedleaf/Starlight#139]
Why was v1.0.1 archived on curseforge? this affects modpacks. is it due to a bug? and 1.0.0 is now the recommended version?

**Comment by DioEgizio** [comment]
https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files/3667412 expect it's not

**Comment by itsdinkd** [comment]
Except it is. That is forge.

**Comment by DioEgizio** [comment]
Oh

https://www.curseforge.com/minecraft/mc-mods/starlight/files/3667443 is the raccomended version right now

**Comment by Spottedleaf** [comment]
I don't remember why I archived it. So I'm not going to unarchive it at this stage unfortunately, there may have been a bug or compatibility problem with later versions.
