### ISSUE TITLE
Still not compatible with Tic-Tacs, Unfortunately 

### ISSUE THREAD

**Issue by QPCrummer** [Spottedleaf/Starlight#14]
I upgraded to the latest starlight, 0.0.2 RC2, and now Tic-Tacs and Starlight are not compatible anymore. I am using Tic-Tacs 0.1.3, which made your mod compatible with it. Now with the latest release of starlight, something got changed and is now not functioning with Tic-Tacs. 
![Cap](https://user-images.githubusercontent.com/66036033/103096871-65025600-45d3-11eb-8396-3f9c3ea474f5.JPG)

**Comment by Spottedleaf** [comment]
yes an update to improve compatibility by no longer screwing around with scheduling broke it (this is better long term)
at this point I'm basically done with significant changes to ABI, so they'll just have to update again
