### ISSUE TITLE
[Fabric 1.18.2] Whenever light updates world flickers

### ISSUE THREAD

**Issue by ZviWolf** [Spottedleaf/Starlight#142]
whenever the light updates, like when i place a lightsource, use dynamic lights, or break/place a block, the terrain flickers for a moment, have tested without starlight, no issue

**Comment by Tinkeshwar-Maharaj** [comment]
> whenever the light updates, like when i place a lightsource, use dynamic lights, or break/place a block, the terrain flickers for a moment, have tested without starlight, no issue

I have the same issue and im unable to find a solution for it, its really annoying when it does that

**Comment by Spottedleaf** [comment]
You may want to set the Chunk Builder option to Fully Blocking, I cannot recall whether there were issues with the default option on this for 1.18.2. If you can provide a video showing this behavior with and without starlight (and the corresponding Chunk Builder option) I can look at this again.
