### ISSUE TITLE
Create and Starlight Bug

### ISSUE THREAD

**Issue by StockiesLad** [Spottedleaf/Starlight#143]
Describe the Bug
Crashing upon pressing the button for create configuration.

Reproduction Steps
Install Create and Starlight on Fabric 0.13.3
Press the engineer's googles button on create
Crash
Expected Result
To just open the GUI like every other GUI

Screenshots and Videos
No response

Crash Report or Log
[latest.log](https://github.com/Fabricators-of-Create/Create/files/8308601/latest.log)

Operating System
Windows 10 Home

Mod Version
0.4.0d

Minecraft Version
1.18.1

Other Mods
starlight-1.0.0+fabric.d0a3220

**Comment by StockiesLad** [comment]
can't even build starlight 1.0.1

**Comment by CalebDaMaker** [comment]
There is a mod called starlight+create https://www.curseforge.com/minecraft/mc-mods/starlight-x-create

**Comment by StockiesLad** [comment]
It's for 1.16.5 tho. And also dw bc I did manage to build 1.0.1 anyways!
