### ISSUE TITLE
[Forge] [1.16.5] Server will not fully start up with Starlight x Create

### ISSUE THREAD

**Issue by Subthy** [Spottedleaf/Starlight#144]
So, my server is not starting up with Starlight on already excising worlds. This has happened to both servers that I have. Like it will work normal and everything is perfect, but on day it will just refuse to start up. It will get stuck on like 98% or something and then it will just stop.
It doesn't start generate a crash report, so I will add a log of that day, as that is the only information I can give

Thanks,
Sub

[2022-03-25-3.log](https://github.com/PaperMC/Starlight/files/8362320/2022-03-25-3.log)
.

**Comment by electronicboy** [comment]
Starlight x Create has nothing to do with us, nor is 1.16.5 supported

**Comment by Subthy** [comment]
You have created this mod to help people with performance. Then why do you not fix issues of the mod, but jump to the next version, cause it came out. If you really want to help people, you could maybe fix mod for other versions first and then go to the next one and not be like this. You are legit one of the only mods that does this to 1.16.5 to my knowledge. It doesn't matter if it's starlight or starlight x create, as it's still your mod by the end of the day. Saying that it has nothing to do with you is just an excuse to not do your job. I know coding is hard, I have done it before, but come on man. If you actually care about your work and want to help people, then fix your mod for other versions too. I'm not asking for an update once a week, but maybe once a month or 3 months, that fixes major bugs like this.

**Comment by electronicboy** [comment]
starlight x create is not our mod, this is not a project I interact with much personally either, this is leafs project, and leaf doesn't generally wanna spend the time working on older versions of his mod, as do many other dozen mod authors, but, the fact is here is that you're still not even using our mod.
