### ISSUE TITLE
Curse Forge 1.16.5 file upload.

### ISSUE THREAD

**Issue by Romoslayer** [Spottedleaf/Starlight#145]
Hi, I noticed Starlight is available for forge 1.16.5 (https://github.com/PaperMC/Starlight/releases/tag/1.0.0-RC2 at the bottom of the page) and I was wondering if you could make a file upload to Curse Forge for this version as I would love to include it into my mod pack thank you.

**Comment by Spottedleaf** [comment]
No

**Comment by WolfBV** [comment]
@Romoslayer Use the Starlight x Create version
