### ISSUE TITLE
need version for paper

### ISSUE THREAD

**Issue by mrjason1000** [Spottedleaf/Starlight#147]
i need a version of starlight for paper.

**Comment by electronicboy** [comment]
starlight is already in paper.

**Comment by mrjason1000** [comment]
yes it is in papermc but this is fabric mod and i want for paper servers

**Comment by electronicboy** [comment]
papermc != paper; 
paper is the software, papermc is the organisation
starlight is already inside of paper

**Comment by mrjason1000** [comment]
but this mod is only for fabric and forge i want a version for paper servers so i can use on my paper server

**Comment by InitAuther97** [comment]
> but this mod is only for fabric and forge i want a version for paper servers so i can use on my paper server

Well, latest Paper servers are already using Starlight for their light engine……

**Comment by electronicboy** [comment]
This is the mod version of starlight, yes.
The starlight engine is already inside of the paper server software, as I keep trying to reiterate, you do not need to install it manually as it's already bundled as a core part of the server software.

**Comment by mrjason1000** [comment]
> This is the mod version of starlight, yes. The starlight engine is already inside of the paper server software, as I keep trying to reiterate, you do not need to install it manually as it's already bundled as a core part of the server software.

ok good
