### ISSUE TITLE
[Fabric 1.18.1] Switching from Starlight to Phosphor causes light artifacts on chunk boundaries

### ISSUE THREAD

**Issue by LazyKB** [Spottedleaf/Starlight#149]
When switching my server from Starlight to Phosphor it seems that the light rewriting is having an issue where a given chunk is not checking for light being produced from sources in surrounding chunks, or maybe the opposite. Since Phosphor uses the vanilla format for saving light I assume this also happens switching back to vanilla but thats not tested by me.
![2022-05-02_15 23 22](https://user-images.githubusercontent.com/87291643/166400162-7a48845e-c61d-41e3-8e96-2901681434ce.png)

You can see its not a rendering thing with f3 showing light 0.

**Comment by Spottedleaf** [comment]
Does this happen switching to Vanilla?

**Comment by Spottedleaf** [comment]
No response
