### ISSUE TITLE
0.0.2-RC3 forge version crashes on startup with latest forge build

### ISSUE THREAD

**Issue by PhantomG27249** [Spottedleaf/Starlight#15]
[latest.log](https://github.com/Spottedleaf/Starlight/files/5748919/latest.log)
I attached the startup log.  Hopefully that is of some use.

**Comment by Spottedleaf** [comment]
Oops, I need to specify a refmap.

**Comment by Spottedleaf** [comment]
This fix doesn't warrant another RC, so I've simply updated the existing jars on the release tab. Should be fixed now, re-download the forge version.
