### ISSUE TITLE
[Quilt 1.18.2] Starlight vs Create: Now on the nether roof!

### ISSUE THREAD

**Issue by Fnige** [Spottedleaf/Starlight#152]
Starlight Version: 1.0.2+fabric.89b8d9f
Minecraft Version: 1.18.2
Loader Version: Quilt 0.17.1-beta.2
Create Version: mc1.18.2_v0.4.1+628

Reproduction:
Get that sticky mechanical piston
Get those piston extension poles
Get that hand CRANK (or creative motor)

That sticky mechanical piston? Put it into the air facing downwards
Those piston extension poles? Put it on top of the sticky mechanical piston!
That hand CRANK? Put it on the side, the right one

SPIN THAT HAND CRANK (or sneak and SPIN THAT HAND CRANK)

Crash report: https://gist.github.com/FnigePython/af38c76b3adec02a62f8fb70e1e05f27

**Comment by BrightyLighty** [comment]
Starlight x Create is a third party mod that has nothing to do with the Starlight creator

**Comment by Fnige** [comment]
This does not have starlight x create. That was for forge 1.16.5

This is 1.18.2

**Comment by Spottedleaf** [comment]
May be related to the other issues I'm about to fix, if they still happen on 1.20.2 can re-open with a new log.
