### ISSUE TITLE
Add compatibility with Vanilla Tweak's Warm Glow

### ISSUE THREAD

**Issue by ttrafford7** [Spottedleaf/Starlight#153]
Warp Glow resource pack doesn't work with Starlight

**Comment by ghost** [comment]
Commenting as no progress has been made. Hopefully this can be fixed soon! :)

**Comment by Spottedleaf** [comment]
Appears to work for me locally - Starlight doesn't affect rendering. Are you able to produce screenshots showing that it does not work with only Starlight installed?
