### ISSUE TITLE
Performance Hit When Interacting With Mangrove Roots

### ISSUE THREAD

**Issue by Jordanyay** [Spottedleaf/Starlight#154]
Greetings!

My experience with Starlight on the client side has been good so far except for one thing. My only problem (from what I've noticed) is that there are serious lag spikes when interacting with mangrove roots. This is especially noticable when interacting with mangrove roots in larger volumes.

Since mangrove roots aren't exactly opaque, this may not just be isolated to mangrove roots, but I'm not entirely sure.

I'm aware that Starlight was designed for server-side usage in mind, with that being said, I'm not sure if this issue will be taken into account if it doesn't impact on the overall purpose of the project.

If any testing is needed to gain more information about this, I'm happy to do that.

Thanks.

**Comment by Spottedleaf** [comment]
Starlight affects the computation of light values, which interacting with (i.e not destroying) these blocks shouldn't affect...

**Comment by Jordanyay** [comment]
Correction: I meant interacting as in breaking and placing the mangrove roots.

With that being said, I haven't used Starlight in over a year, so things could have changed since then.

Also, my testing at the time may have been inconsistent and may have resulted in false positives, but I cannot tell for sure.

Feel free to keep this issue closed if you think it's no longer relevant.

Thanks.
