### ISSUE TITLE
[1.18.2][Forge] True Darkness Mod incompatibility

### ISSUE THREAD

**Issue by Charismara** [Spottedleaf/Starlight#156]
Minecraft: 1.18.2
Forge: 40.1.68
Starlight: 1.0.2+forge.546ae87
True Darkness Mod: 2.0.91
True Darkness Issue: grondag/darkness#22

The true Darkness Mod get's fully disabled by Starlight or create some fog in the day (which shouldn't be there) and works in the night when a boss health bar is visible (tested with MineColonies Raid bar). Is there a way to fix that?

**Comment by Spottedleaf** [comment]
I don't see how Starlight would conflict with True Darkness. They don't appear to be modifying anything to do with the light values computed by the light engine or have any hooks.
