### ISSUE TITLE
Rendering error caused in Ars Nouveau

### ISSUE THREAD

**Issue by Shadowex3** [Spottedleaf/Starlight#158]
When playing Ars Nouveau the floating items on top of pedestals (used for various rituals) won't render if starlight is being used. Ars Nouveau's developer's theory was something about how item entities are handled in Starlight.

It's not a critical incompatibility but it does make performing rituals a fair bit harder since there's no way to tell what you have where but pure blind memory.

**Comment by Spottedleaf** [comment]
Starlight doesn't affect item entities.
