### ISSUE TITLE
Failed to light chunk while generating on fabric in the nether

### ISSUE THREAD

**Issue by BillyDaPoop** [Spottedleaf/Starlight#16]
**Server info**
Fabric 1.16.4
Seed: -2680893630548586222
Generating the nether

**Log file**
https://paste.gg/p/anonymous/181792d011d74c61a7bc8bf39bd6999f

**Mods list**
BlueMap-1.3.0-snap-fabric-1.16.4.jar, Chunky-1.1.21.jar, fabric-api-0.29.0+1.16.jar, fabric-language-kotlin-1.4.21+build.1.jar, Lakeside-1.0.3+1.16.4.jar, lithium-fabric-mc1.16.4-0.6.0.jar, mostructures-1.0.1+mc.1.16.4.jar, simplexterrain-0.7.2.jar, starlight-fabric-0.0.2-RC3.jar, upstream-1.0.1.jar

**Datapack list**
incendium-v3-1-7, newvanilla-1-4-1-cegress

**Comment by klaydev** [comment]
Regenerate map. Delete nether, world, end

**Comment by Spottedleaf** [comment]
Basically, something was writing to the chunk starlight was trying to light. Given just how many chunks exploded, it's probably another mod stepping way out of bounds when it's populating chunks. If you can produce without starlight, I can re-open the issue.
