### ISSUE TITLE
Crash when exploring the end using Fokastudios Ender Expansion with Starlight.

### ISSUE THREAD

**Issue by TheFantasticLoki** [Spottedleaf/Starlight#163]
Crash starts at line 7614: https://mclo.gs/cILs5tm
This is an error me and foka have been trying to solve ourselves for days thinking it's a problem with his pack. But he's fixed basically every other problem we were getting crashes for aside from this one which still lingers. While we thought it was a worldgen issue I am starting to believe it's a problem with starlight as removing it seems to prevent the crash. If you have any ideas as to what is causing this we would love to hear it as this little crash has been the bane of our past 2 days.

**Comment by Spottedleaf** [comment]
I don't see anything running through Starlight's code path (ignore the failed to light log, that's just how an error may propagate through the Vanilla chunk system), so I honestly don't know. And given this happened 1 year ago...
