### ISSUE TITLE
Large shadows after blowing up lots of TNT

### ISSUE THREAD

**Issue by AverageTurtle** [Spottedleaf/Starlight#165]
This could be a compatibility issue sense the server is running geyser! It is a fabric 1.19.2 server (fabric 0.14.10)

Mods on server:
- carpet-tis-addition-mc1.19.2-v1.41.1.jar | 1.31MB | 08/11/2022 07:10:49 |  
- Chunky-1.3.38.jar | 299.67kB | 08/11/2022 07:35:02 |  
- fabric-api-0.64.0+1.19.2.jar | 1.67MB | 08/11/2022 07:10:50 |  
- fabric-carpet-1.19.2-1.4.84+v221018.jar | 1.46MB | 08/11/2022 07:10:50 |  
- fabric-language-kotlin-1.8.5+kotlin.1.7.20.jar | 6.13MB | 08/11/2022 07:10:52 |  
- ferritecore-5.0.0-fabric.jar | 116.32kB | 08/11/2022 07:10:30 |  
- floodgate-fabric.jar | 11.77MB | 08/11/2022 07:10:35 |  
- Geyser-Fabric.jar | 12.69MB | 08/11/2022 07:10:39 |  
- ledger-1.2.5.jar | 15.79MB | 08/11/2022 07:10:45 |  
- lithium-fabric-mc1.19.2-0.10.1.jar | 530.36kB | 08/11/2022 07:10:45 |  
- spark-1.9.40-fabric.jar | 2.62MB | 08/11/2022 07:10:46 |  
- starlight-1.1.1+fabric.ae22326.jar | 124.48kB | 08/11/2022 07:10:46 |  
- styledplayerlist-2.2.2+1.19.1.jar | 126.76kB | 08/11/2022 07:27:48 |  
- vanish-1.19.1-1.4.3.jar | 59.54kB | 08/11/2022 07:35:02 |  
- voicechat-fabric-1.19.2-2.3.12.jar | 7.99MB | 08/11/2022 07:10:49 |  
- worldedit-mod-7.2.12.jar

![2022-11-08_11 18 06](https://user-images.githubusercontent.com/21147423/200619487-d6b4d060-c370-47c5-a7d9-fdf88e27f449.png)

**Comment by Spottedleaf** [comment]
This is likely a result of the behavior in 1.19 that sends light data directly when the number of blocks broken in a chunk section exceeds 64. This is specific to how Vanilla manages block syncing to the client, so nothing to do with Starlight. I used to have some fixes that would alleviate the issue slightly, but I dropped them and didn't bother to improve them as it's really a Vanilla problem unrelated to the lighting engine.

However, in 1.20.something they removed the behavior I described which should actually fix the issue. So the solution would be to update.

If you can produce the behavior on 1.20.2 I can look at fixing it, but in my experience in blowing up large amounts of TNT it's not an issue.
