### ISSUE TITLE
Dead link in TECHNICAL_DETAILS.md

### ISSUE THREAD

**Issue by xavierbradford** [Spottedleaf/Starlight#169]
The link on line 85 of TECHNICAL_DETAILS.md goes to an ad page now, consider replacing it with an archive.org link: https://web.archive.org/web/20210622035752/https://www.seedofandromeda.com/blogs/29-fast-flood-fill-lighting-in-a-blocky-voxel-game-pt-1

**Comment by giorov** [comment]
Good idea!

**Comment by Spottedleaf** [comment]
resolved by 5954ecc4bf4bac5d1644272ec7e01de7e08fde6c and 9be13e3f138f6573f6cc1aa2818c556a5b30805d
