### ISSUE TITLE
Still having chunk lag issues

### ISSUE THREAD

**Issue by QPCrummer** [Spottedleaf/Starlight#17]
I have the latest of everything. Starlight, Lithium, Tic-Tacs. I still get a pause when going in-between chunk borders. I have starlight server-side and client-side. My server runs on an Intel Xeon, so I don't think hardware is the issue. My server also has 8gb of ram, which is plenty enough for twenty players total (only 1-4 on at a time).

 
I wish I could give you the video evidence, but it is larger than 10MB ):

**Comment by QPCrummer** [comment]
It does get very annoying during elytra flight. It isn't high priority, as the game is still playable. It is just one of those quality of life things.

**Comment by Spottedleaf** [comment]
From the performance numbers I've seen locally, in my experience it's actually just the rendering of these new chunks being loaded in that's causing spikes. While I want to fix issues like these, if it's not caused by the lightengine I really can't do anything from starlight.
