### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by NotDemonix** [Spottedleaf/Starlight#171]
Hello, i have this mod on my fabric server. After flying a bit ram goes to full, i have 6gb allocated to my mc server on my vps, any ideas?

**Comment by MWHunter** [comment]
how are you measuring memory usage?

**Comment by Chew** [comment]
> Warning: Memory usage on modern garbage collectors is not a stable value and it is perfectly normal to see it reach max. Please do not pay it much attention.

Or something. The issue is more than likely you flying and loading chunks.

**Comment by Spottedleaf** [comment]
Unless the server is out-of-memory erroring this is normal.
