### ISSUE TITLE
Micro stutters

### ISSUE THREAD

**Issue by WildGrapefruit223** [Spottedleaf/Starlight#172]
Every time I explore chunks in my single player I get micro stutters.

**Comment by MWHunter** [comment]
does this happen without starlight?

**Comment by WildGrapefruit223** [comment]
No, but I think that i fixed it, somehow it works fine now.
Thank you for your time

**Comment by StormDragon-64** [comment]
If you fixed it, can you close the issue and maybe state how you fixed it?

**Comment by WildGrapefruit223** [comment]
I forgot to install another mod (lithium) to improve the tps
