### ISSUE TITLE
[Forge 1.16.5] Incompatibility with some RedPower Illumination lights, CBMultipart?

### ISSUE THREAD

**Issue by qwertie64982** [Spottedleaf/Starlight#174]
**I just realized that this issue was submitted to PaperMC/Starlight, not [SirOMGitsYOU/Starlight](https://github.com/SirOMGitsYOU/Starlight). The latter's [mod page](https://www.curseforge.com/minecraft/mc-mods/starlight-x-create) links here for submitting issues. If this is in error, please disregard this issue report.** 

## Description

With only ProjectRed Illumination (and dependencies), lights work fine. When I add Starlight x Create, the light sources which aren't a full block stop emitting light. CBMultipart seems more likely to cause an incompatibility than ProjectRed. 

## Screenshots

Without Starlight x Create

![2023-02-22_18 02 19](https://user-images.githubusercontent.com/13337981/220806811-25708f90-c4ae-4af9-8c44-b7ebe2c3a92a.png)
![2023-02-22_18 02 29](https://user-images.githubusercontent.com/13337981/220806827-26ea1462-2e9c-428d-b728-b22894e15d7c.png)

With Starlight x Create

![2023-02-22_18 01 24](https://user-images.githubusercontent.com/13337981/220806793-6696b59c-c615-4569-a217-8700eb39d26f.png)
![2023-02-22_18 00 59](https://user-images.githubusercontent.com/13337981/220806862-963aaf9e-620a-43f3-bfac-6282bd207bb7.png)
![2023-02-22_18 04 26](https://user-images.githubusercontent.com/13337981/220806888-10f046e3-62ab-4b3f-bb38-b2e33c776984.png)

## Config

* Minecraft 1.6.5 on Windows 10
* Forge 36.2.39
* Starlight x Create 1.2
* Scorge 3.1.3
* CBMultipart 3.0.4.123-universal
* CodeChickenLib 4.0.7.445
* CoFH Core 1.5.2.22
* ProjectRed Core 4.12.0
* ProjectRed Illumination 4.12.0

**Comment by Spottedleaf** [comment]
>Report any issues here: [Starlight X Create Issue tracker](https://github.com/SirOMGitsYOU/Starlight)
