### ISSUE TITLE
TECHNICAL_DETAILS.md blog link is now compromised and redirects to a malicious site 

### ISSUE THREAD

**Issue by ErrorRaffyline0** [Spottedleaf/Starlight#176]
It seems the domain that hosted the blog page about light decreases has been compromised. It now leads to a website that is meant to phish the user.

**Comment by ErrorRaffyline0** [comment]
Note: this is a link that is contained in the text of TECHNICAL_DETAILS.md

**Comment by Spottedleaf** [comment]
>https://github.com/PaperMC/Starlight/issues/176

Yeah I should have done something about this sooner. I'll update it now.

**Comment by Spottedleaf** [comment]
resolved by 5954ecc4bf4bac5d1644272ec7e01de7e08fde6c and 9be13e3f138f6573f6cc1aa2818c556a5b30805d
