### ISSUE TITLE
Question/Suggestion (Colored Light)

### ISSUE THREAD

**Issue by TwinShards** [Spottedleaf/Starlight#178]
Is there any possible chance to add colored lighting based on the block's ID?

**Comment by mrjasonn** [comment]
This is not a vanilla Minecraft feature so very most likely this won't be added to Starlight.

**Comment by TwinShards** [comment]
> This is not a vanilla Minecraft feature so very most likely this won't be added to Starlight.

"Fabric mod for completely rewriting the vanilla light engine."

This mod is not rewritting/improving the vanilla light engine and therefor there might be an open door for SpottedLeaf to add per-block (RGB) light. At this current time only a default set color is apply to everything and a light intensity rule the light amount.

**Comment by Spottedleaf** [comment]
Starlight does not touch rendering code which is a very good thing. It only touches the light engine, and I have no plans to make any non-vanilla feature changes.
