### ISSUE TITLE
[Request] Update the comparison graph in README.md

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Spottedleaf/Starlight#18]
I've heard (and felt) that Phosphor 0.7.0 dev branch is much better than 0.6.0 and almost as good as Starlight, so maybe it may be a good idea to show Phosphor 0.7.0 in the graph either by editing the phosphor section or adding a new section for 0.7.0 and renaming the old one to specify 0.6.0?

**Comment by Spottedleaf** [comment]
When I was doing performance testing I had actually found that 0.7.0 made small regressions (10% worse) with respect to chunk generation performance. I had asked the devs about this, and they had replied 0.7.0 was more targeted towards reducing worst-case scenario performance. 

I could tell locally that 0.7.0 had fixed the light engine problems crossing chunk borders, so 0.7.0 really did fix some worst-case scenario performance. I've plans to do more comparisons that highlight stuff _other than_ generation.
