### ISSUE TITLE
 Crash due to uninitialised nibble arrays during block light propagation with Create

### ISSUE THREAD

**Issue by Inonedn** [Spottedleaf/Starlight#186]
[crash-2023-07-14_21.04.33-client.txt](https://github.com/PaperMC/Starlight/files/12059819/crash-2023-07-14_21.04.33-client.txt)

**Comment by willjouo** [comment]
Spend a full hour searching on which mod was crashing my game when doing stuff with Create, and it's Starlight :(

- Minecraft 1.20.1 with just two mods installed:
  - Create (create-1.20.1-0.5.1.d.jar)
  - Starlight (starlight-1.1.2+forge.1cda73c.jar)
- Forge 47.1.0

I can reproduce a crash by creating a simple elevator and then right clicking on the elevator pulley block to activate the elevator.
I can provide a Create schematic as an .nbt file to easily reproduce the issue.

[crash-2023-07-15_17.31.26-client.txt](https://github.com/PaperMC/Starlight/files/12062013/crash-2023-07-15_17.31.26-client.txt)

**Comment by mjel72** [comment]
My issue is with the Windmill bearing with Starlight installed I get an immediate crash when starting the windmill. Disable Starlight and no issues. 

Version of Minecraft 1.20.1 
Forge 47.1.0 
Starlight-1.1.2+forge.1cda73c.jar  
Create-1.20.1-0.5.1.d.jar

**Comment by mettemfurfur000** [comment]
Same issue, but on fabric

[tl-logger8955619784843542567.txt](https://github.com/PaperMC/Starlight/files/12775218/tl-logger8955619784843542567.txt)

Only client crashed, not server :heart_decoration:

**Comment by OfficialLahusa** [comment]
I was able to replicate this on Fabric:

Minecraft 1.20.1
starlight-1.1.2+fabric.dbc156f
create-fabric-0.5.1-d-build.1161+mc1.20.1
fabric-api-0.88.1+1.20.1

[crash-report.txt](https://github.com/PaperMC/Starlight/files/12818752/crash-report.txt)

**Comment by liamwerk7676** [comment]
same with me when i make a train i dont have a crash log right now but i hope starlight fixes this isue becuss then i can have good preformance
