### ISSUE TITLE
crash with ae2

### ISSUE THREAD

**Issue by Mari023** [Spottedleaf/Starlight#187]
### Describe the bug

The game crashes when viewing a scene in ae2s guide book
### How to reproduce the bug
- Install ae2
- hold w on a sky stone block to open the guide
### Expected behavior

It should show the guide page, with a rendered scene
### Additional details

originally reported on ae2s issue tracker:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7275, https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7246
### Which minecraft version are you using?

1.20.1
### On which mod loaders does it happen?

Fabric, tho the same issue should also apply to forge
### Crash log
https://gist.github.com/Mari023/3f55b27c9eeedbd68b5e25a1779b5316

### Analysis 
Starlight does not provide a default implementation for ExtendedWorld#getAnyChunkImmediately, which causes a crash if other mods implement their own level and render it, but don't extend ClientLevel (or implement ExtendedWorld themself)
https://github.com/PaperMC/Starlight/blob/acc8ed9634bbe27ec68e8842e420948bfa9707e7/src/main/java/ca/spottedleaf/starlight/common/world/ExtendedWorld.java#L12

**Comment by Spottedleaf** [comment]
See https://github.com/PaperMC/Starlight/pull/188#issuecomment-1765403646

**Comment by BookerCatch** [comment]
It's back.
[latest.log](https://github.com/PaperMC/Starlight/files/13665794/latest.log)

**Comment by Mari023** [comment]
> It's back. [latest.log](https://github.com/PaperMC/Starlight/files/13665794/latest.log)

no.
the fix was only released for 1.20.2+

**Comment by BookerCatch** [comment]
I must be tripping then. Could have sworn at some point it was working a week ago or so.

**Comment by Weylend** [comment]
Crashes me too
Is there a backport planned?

**Comment by Octelly** [comment]
The original bug was described for 1.20.1, where the bug still persists. I don't think this issue should be marked as closed, although a wontfix would suck :(

(tested on Forge 1.20.1)
