### ISSUE TITLE
holes in world

### ISSUE THREAD

**Issue by redstonerti** [Spottedleaf/Starlight#19]
Sometimes, there are areas where the terrain never loads no matter how long you wait and they never go away even if you get out of your world and come back in
![image](https://user-images.githubusercontent.com/48157961/103821594-2d85b600-5077-11eb-8a47-0795ce95febb.png)

I even tried relaunching minecraft but it still doesn't work
I'm in 1.16.4 with version starlight-fabric-0.0.2-RC3
i also have lithium, sodium and tic tac installed but starlight is most likely the cause

**Comment by Aurelien30000** [comment]
Does this issue also occur on the lastest release _(https://github.com/Spottedleaf/Starlight/releases)_? Please try :)

**Comment by redstonerti** [comment]
![image](https://user-images.githubusercontent.com/48157961/103826671-ef40c480-507f-11eb-923f-daaa4569142c.png)
Yes and in the same spot

This is the hermitcraft season 6 world but i've had it happen to me before in my own worlds

Edit: i took starlight out and this is still happening, sorry this might be another mod's fault. I will now remove this post
Also, jellysquid can you please remove this?

**Comment by Spottedleaf** [comment]
If there are any logs you can post with starlight (while loading this area) I'd like to see them

**Comment by redstonerti** [comment]
@Spottedleaf Sorry, i have found the issue, i had an outdated version of sodium which was interfering. Now that both starlight and sodium are up to date, i no longer have this problem (btw this was preventing the world from saving). Do you still want to see the logs though?

**Comment by Spottedleaf** [comment]
If everything's working fine after updating, there's no real need to do anything further. If it pops up again, you can reply here with screenshots & logs.
