### ISSUE TITLE
Not working with LambDynamicLights

### ISSUE THREAD

**Issue by sunnythe1** [Spottedleaf/Starlight#192]
LambDynamicLights is a mod that that adds more stuff to the Lights and stuff idk what to put here just can you flx it?

**Comment by PikachuGabe** [comment]
mod appears to be incompatible with anything that changes how lighting works, eg true darkness, and is set to override them

**Comment by Felix14-v2** [comment]
LambDynamicLights was compatible with Starlight, and you didn't provide any diagnostic info.

**Comment by Spottedleaf** [comment]
I don't see any code that would make it incompatible, without any logs either I don't think I can do anything.
