### ISSUE TITLE
Official quilt compatibility??

### ISSUE THREAD

**Issue by Feliks-WR** [Spottedleaf/Starlight#195]

**Comment by electronicboy** [comment]
<img width="815" alt="Screenshot 2023-09-20 at 14 31 12" src="https://github.com/PaperMC/Starlight/assets/1228900/f01ded09-b45c-4a6f-a90c-7a139f9a7168">
Given mojangs improvements to the vanilla server software, I really doubt that there is any interest in porting the software to more platforms given the current state of this mod
