### ISSUE TITLE
Starlight crashes on world load

### ISSUE THREAD

**Issue by QuantumRange** [Spottedleaf/Starlight#199]
When I loaded my Minecraft world, the world stayed open for a bit and then crashed, it was night time (The world was a couple hours old before this started happening).
I got this crash report: [crash-2023-11-09_20.51.33-client.txt](https://github.com/PaperMC/Starlight/files/13306927/crash-2023-11-09_20.51.33-client.txt)
The log shows a illegal exception here:
https://github.com/PaperMC/Starlight/blob/5867eae3b82abe3ef1387e60bc86752d9cda63fb/src/main/java/ca/spottedleaf/starlight/common/light/BlockStarLightEngine.java#L78

**Comment by Spottedleaf** [comment]
This looks like https://github.com/PaperMC/Starlight/issues/186, which is fixed in Starlight 1.1.3.
