### ISSUE TITLE
Network Compatible?

### ISSUE THREAD

**Issue by Jayfin1** [Spottedleaf/Starlight#20]
You're re-writing the lighting engine, is it going to stay network compatible? If you change the lighting model, it'll require a client.

**Comment by Aurelien30000** [comment]
Startlight is compatible with clients and servers but not necessary on both :)

**Comment by Spottedleaf** [comment]
It's been designed to be network compatible, so it should work if it's just on the client or just on the server. If it's not working for some reason, you can file a bug report.
