### ISSUE TITLE
Worlds do not load/create

### ISSUE THREAD

**Issue by KorbynTalks** [Spottedleaf/Starlight#200]
This is probably a compatibility issue because I have a dozen other mods.

If you wanna know what mods I use let me know

**Comment by toinouH** [comment]
Without providing any logs or mod list we won't be able to help you ^^"

**Comment by bigtruckin78** [comment]
Just experienced the same issue. I'm using Starlight in ATM 9. It was working fine up until last night. Then today the instance wouldn't load. I've attached what i think is the correct log. If not I can get something else. FWIW the last mod I was playing with was EnderIO.
[debug-2.log](https://github.com/PaperMC/Starlight/files/13358157/debug-2.log)

**Comment by ZestyBlaze** [comment]
Yeah seems to be EnderIO's Flywheel Compat I think

**Comment by Spottedleaf** [comment]
Duplicate of https://github.com/PaperMC/Starlight/issues/197
