### ISSUE TITLE
Starlight crashes when used in combination with Create mod

### ISSUE THREAD

**Issue by ciekals11** [Spottedleaf/Starlight#201]
Minecraft version: 1.20.1
Fabric version 0.14.24
Starlight version: 1.1.2+1.20
Create version: 0.5.1-d-build.1161+mc1.20.1

Description:

When creating create contraption (tested with [Elevator Pulley](https://create.fandom.com/wiki/Elevator_Pulley)) minecraft crashes

Log:
[crash-on-create-contraption.txt](https://github.com/PaperMC/Starlight/files/13430296/crash-on-create-contraption.txt)

Then when loading into same world it crashes again
[crash-on-world-load.txt](https://github.com/PaperMC/Starlight/files/13430297/crash-on-world-load.txt)

**Comment by Spottedleaf** [comment]
This looks like https://github.com/PaperMC/Starlight/issues/186, which is fixed in Starlight 1.1.3.
