### ISSUE TITLE
Rerelease for 1.20.4 - It's the exact same

### ISSUE THREAD

**Issue by mucookul** [Spottedleaf/Starlight#205]
Can you please re-release for 1.20.4, is just has a major bugfix: https://feedback.minecraft.net/hc/en-us/articles/22046600558221-Minecraft-Java-Edition-1-20-4

**Comment by mucookul** [comment]
#204 has it

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Starlight/commit/f5dcd1a4278aba0aceb92a64bb91d411154449f7
