### ISSUE TITLE
About #186. Is Starlight 1.1.3 compatible with 1.20.1?

### ISSUE THREAD

**Issue by VOLKOUL** [Spottedleaf/Starlight#208]
So I get the same (presumably) crash as in https://github.com/PaperMC/Starlight/issues/186
As stated, the issue was fixed in 1.1.3, however it is marked for 1.20.2 and not 1.20.1
I was wandering whether 1.1.3 is compatible with 1.20.1
Thank you.

**Comment by Spottedleaf** [comment]
No
