### ISSUE TITLE
Upload to curseforge

### ISSUE THREAD

**Issue by RangoMcRoony** [Spottedleaf/Starlight#21]
I'm not 100% sure if this is the right place to put this (if not i will take down the comment), but the reason i state this as an issue is because many server hosting sites only allow certain mods that have been uploaded to recognised sites. Hence it would be advantageous to upload this to curseforge with a disclaimer that it is still in early stages. Either way, you have done an excellent job here and are an asset to the community

**Comment by K0-RR** [comment]
+1

**Comment by Spottedleaf** [comment]
When I can verify that starlight is stable enough to meet my standards i will post it. From what I can tell, there's not really any lighting problems left (except for 1 problem).
