### ISSUE TITLE
Mod pack inclusion?

### ISSUE THREAD

**Issue by PhantomG27249** [Spottedleaf/Starlight#22]
Do you have a specific policy for inclusion in a pack. I am working on a github repo pack for fabric optimization mods. I want to include starlight. Is that fine if I cite the repo and your name in the sources file? Sorry to make an issue report of it I didn't know how else to reach you.

**Comment by Spottedleaf** [comment]
The general rules of the LGPLv3 apply, if you make modifications you must distribute the source.
