### ISSUE TITLE
Weird rendering

### ISSUE THREAD

**Issue by redstonerti** [Spottedleaf/Starlight#23]
So i made a massive 26,650 x 26,650 screenshot of a world at 64 chunk render distance but it has a million weird rendering bugs. Blocks appear above other blocks when they should, leaves become hollow, there are black seams everywhere and i'd like to know what you think is causing these issues or where i could start
These are my mods:
![image](https://user-images.githubusercontent.com/48157961/105549012-139bd280-5d09-11eb-989b-b7b5cf659212.png)
This is the image:
http://www.gigapan.com/gigapans/224366
(They are a lot more pronounced on the edges of the map)

This was captured with normal fov at y 1300. I tried the same thing with 30 fov but at y 3000 in order to see the same things and the problems got way worse
Does this have to do with starlight or is it something else or is it just vanilla?
If it is so, do you think any of the mods i have do something to fix it or is it just impossible?

**Comment by shuyuan-liu** [comment]
Remove all mods / move them to another folder so they don't get loaded, and try taking your screenshot again. If the problem persists then it's a vanilla issue, not Starlight. If not, add mods back one at a time and try your screenshot each time. When the problem returns then you know it's the last mod you added back that's causing the problem in some way.

I don't think anyone could possibly tell which mod is causing the glitch just by looking at your folder contents, so I would suggest you exepriment by yourself and see if you can find the cause. Hope that helps!

**Comment by Spottedleaf** [comment]
I don't notice any lighting specific problems, so if you can't produce these issues without starlight i can't really help you.

I also don't know the rendering system, so I can't really even begin to question it rendered that way.

**Comment by redstonerti** [comment]
Thanks for the help, now i at least know where to start. I just wanted to know in my original question if there were any mods i had related to these rendering issue. I'll open this again when i have more information
(I also fixed the link so it actually takes you to the image not github)

The only problem is that i used most of these mods in order to produce this image, and i even had to use my brother's computer which has more vram so i could get to 26,650 x 26,650. It's ok though, the issues present themselves on smaller resolutions as well and even in just normal gameplay. They are just too small normally to ever be taken into consideration. I'll just render at lower resolutions and less chunks. You would still be able to see them clearly

**Comment by redstonerti** [comment]
I have found out that the problem can be attributed only to sodium. Sorry i posted in the wrong mod's forum
