### ISSUE TITLE
(Question) Is starlight safe to use via clients during reproduction?

### ISSUE THREAD

**Issue by Kichura** [Spottedleaf/Starlight#24]
I usually never ask something like this before but; Can starlight be safely used in reproduction environments such as hypixel or other worlds without it causing issues in process?

The reason why i bring this up is because i planned to switch from phosphor to starlight all together to try and make the lighting engine 'improved' in some cases.

**Comment by GaiaB0t** [comment]
_for servers like hypixel just use 1.8, it works best_

**Comment by Kichura** [comment]
> 
> 
> _for servers like hypixel just use 1.8, it works best_

I do not wish to switch back to 1.8 as i have suffered through multiple problems even if lunar client and others were involved during this. But thanks for this suggestion anyways.

**Comment by Spottedleaf** [comment]
In general as long as starlight isn't on CF it doesn't really have my prod-ready stamp of approval. The notable exception is starlight on tuinity, https://github.com/Spottedleaf/Tuinity/commit/d3ee22224addb3d6997feedf4eba95962786f7d7 which will run starlight in production. I expect to post to CF relatively soon, as there are no major problems that I know of for starlight.

So it's mostly safe.
