### ISSUE TITLE
Upstream updates in tuinity?

### ISSUE THREAD

**Issue by SizzlinSeal01** [Spottedleaf/Starlight#27]
I know that it is still in beta, and might not even work out, but, eventually, when it is stable, having starlight work as an upstream for tuinity will make tuinity EXTREMELY fast.

I think that if starlight gets added to tuinity, it will become very popular and honestly I dont really want to swap to a fabric server but I will if I cant get starlight along with bukkit plugins (when it is stable of course)

**Comment by Spottedleaf** [comment]
https://github.com/Spottedleaf/Tuinity/blob/master/patches/server/0061-Rewrite-the-light-engine.patch

Starlight was initially designed for tuinity and landed in the main branch a while ago.
