### ISSUE TITLE
Missing homepage and issues tags inside the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [Spottedleaf/Starlight#28]
Please don't be mad for reporting something so pointless.

**Comment by K0-RR** [comment]
Can I ask why it is not merged?

**Comment by DragonEggBedrockBreaking** [comment]
> Can I ask why it is not merged?

I'm assuming the following:
The pull request that implemented it also added GitHub Actions, but many ppl were unhappy with how it was done. I made an alternative GitHub Actions implementation, but I didn't include a fix to this in the PR. Most likely the commit will be cherry picked from #30 when one of the GitHub Actions implementations are also merged.

**Comment by DragonEggBedrockBreaking** [comment]
The issues tag was added, so the issue report title should just include 'homepage' tag

**Comment by Spottedleaf** [comment]
I'll update homepage to CF when I publish there

**Comment by Spottedleaf** [comment]
Resolved in 1.0.0
