### ISSUE TITLE
[Forge] Incompatibility with Miner's Helmet

### ISSUE THREAD

**Issue by Matthysse** [Spottedleaf/Starlight#29]
Hello!
The Miner's Helmet from the same name mod doesn't light around us when weared with this mod installed:
![2021-02-01_12 51 31](https://user-images.githubusercontent.com/32510957/106494009-2a38eb00-64ba-11eb-8257-9562fe68d896.png)

**Comment by Spottedleaf** [comment]
I looked over their code, and they inject pretty deep into the light engine. So there's not much I can do about that one.

**Comment by Matthysse** [comment]
No problem, I removed this mod, it makes the game lag when entities wear it.
