### ISSUE TITLE
[1.16.5-Forge]Server crash

### ISSUE THREAD

**Issue by EnterFor** [Spottedleaf/Starlight#31]
https://paste.ubuntu.com/p/hRtMjHXC56/
Nothing strange happened before the crash, when I restarted, the game runs normally.

**Comment by EnterFor** [comment]
I don’t know which side the problem belongs to, so I also submitted a bug to him.
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/issues/1

**Comment by Genau6502** [comment]
This isn't a starlight issue
