### ISSUE TITLE
[1.16.5-Forge]server stopped

### ISSUE THREAD

**Issue by EnterFor** [Spottedleaf/Starlight#33]
Forge:36.0.22
https://paste.ubuntu.com/p/myqQPNTWkZ/
I don’t know if the problem belongs to Starlight
The server stopped but did not crash

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/107911249-1cde2f00-6f97-11eb-920c-ee9c93242f62.png)
Stopped again, no strange things happened.
The information for each crash is somewhat different

**Comment by a8underscore** [comment]
can you give the second crash in text format? maybe post on paste.gg or paste.ubuntu like u did earlier?

**Comment by Spottedleaf** [comment]
Next version will fix this.

**Comment by Spottedleaf** [comment]
Fixed by 1.0.0-RC1
