### ISSUE TITLE
Client-server light value desync with moving blocks

### ISSUE THREAD

**Issue by JonasStorm** [Spottedleaf/Starlight#36]
When moving blocks away from a light source and back the client light value (as from the Debug Menu) and server light value (as from the debug menu) desync, occasionally in some configurations.  To be specific, the client light level maintains how it was when the blocks were removed when they've returned. It may be of note that I'm returning the blocks in the same gt.
![2021-03-06_02 51 29](https://user-images.githubusercontent.com/73087261/110204659-17069b80-7e29-11eb-8316-35ce3d4a0c91.png)
![2021-03-06_03 24 05](https://user-images.githubusercontent.com/73087261/110205121-87162100-7e2b-11eb-8938-0700992016d1.png)

**Comment by Spottedleaf** [comment]
If you can provide me the setup used to create that desync i can take a look at it locally (as well as a list of mods installed)

**Comment by JonasStorm** [comment]
I was unaware of this at the time of making, but this _actually_ seems to just be part of litematica pasted structures not having their light handled properly, but less verbosely than the light appearing to be wrong from the point of pasting, as does sometimes occur.
The setup I was using can be found here 
(https://cdn.discordapp.com/attachments/765384567103553537/824847549956489226/lIGHT_TEST_THING.litematic)
Here (https://youtu.be/QW6R9R83qXw) is a video of it occurring. (using masa's minihud to show light levels on top of blocks, the aforementioned litematica, and carpet mod's creativenoclip to phase through blocks)
My mods list: https://paste.ee/p/Lp34W

**Comment by JonasStorm** [comment]
After extensively testing with the newest version of this mod, I have experienced none of the issues mentioned in here.
