### ISSUE TITLE
No mod icon

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [Spottedleaf/Starlight#37]
No mod icon in ModMenu

**Comment by Spottedleaf** [comment]
I've generally no plans to make one right now

**Comment by Big-Iron-Cheems** [comment]
I suggest using this as image (looks nice and the pixel style makes it minecraft-like in a way 🌟):
![icon](https://user-images.githubusercontent.com/52252627/126702717-f766b004-08f6-455c-9f79-c14d329f7a78.png)

**Comment by JRoy** [comment]
> I suggest using this as image (looks nice and the pixel style makes it minecraft-like in a way 🌟):
> ![icon](https://user-images.githubusercontent.com/52252627/126702717-f766b004-08f6-455c-9f79-c14d329f7a78.png)

Any icon must be original content, not an image you find online

**Comment by MaxBr5** [comment]
You don't really need one but it just looks nice.

**Comment by Spottedleaf** [comment]
Resolved in 1.0.0
