### ISSUE TITLE
Special block rendering can't be illuminated

### ISSUE THREAD

**Issue by Matthysse** [Spottedleaf/Starlight#39]
Hello!

A mod called Supplementaries adds a new block called the Notice Board. It's like an item frame, but as a block, that can display maps and books.
The problem is that with Starlight installed, the light around it doesn't seem to affect the rendering of the map:

Without Starlight (rendered normally):
![2021-02-28_22 01 20](https://user-images.githubusercontent.com/32510957/112447902-1ee39c80-8d52-11eb-836a-9a31fc029911.png)

With Starlight (even with a lot of light sources, the map is always dark):
![2021-02-28_21 59 26](https://user-images.githubusercontent.com/32510957/112448076-4c304a80-8d52-11eb-81c7-e1b9e37dd9b8.png)

**Comment by Spottedleaf** [comment]
It looks like you have a lot more mods added in that second screenshot than starlight...

**Comment by Matthysse** [comment]
Oops sorry I did some testings and you're right, that's specific to Seus shaders (not even Optifine), my bad I close the issue.
