### ISSUE TITLE
[Feature request] Fix bug with vanilla smooth light

### ISSUE THREAD

**Issue by Zailer43** [Spottedleaf/Starlight#4]
### Expected Behavior
![2020-11-26_21 49 27](https://user-images.githubusercontent.com/63565983/100399384-51de8380-3031-11eb-96cd-b5cad78c35d7.png)

### Actual Behavior
![2020-11-26_22 34 21](https://user-images.githubusercontent.com/63565983/100399186-8bfb5580-3030-11eb-9223-4e84f0f22fc1.png)

### Reproduction Steps

1. Activate in the smooth light in graphics options
2. Choose one of the following blocks
![image](https://user-images.githubusercontent.com/63565983/100399420-881c0300-3031-11eb-957d-18afe34cdb2c.png)
(It can be any slab or stair, the piston must be extended)

3. Place light
4. Lock yourself in a 1x2x1 where the light arrives and leave the chosen block as a roof

**Comment by Spottedleaf** [comment]
This mod is only for modifying the light engine, not the client rendering system.
