### ISSUE TITLE
[1.17] Light is not updated

### ISSUE THREAD

**Issue by toficzko** [Spottedleaf/Starlight#40]
After migrating my minecraft 21w10a vanilla server to fabric with latest starlight from releases (happens when Compiled locally too) The light is getting corrupted , What i mean by that is all light sources only illuminate one block , this happens on a clean server too 

Here are some screenshots:

Vanilla:
![vanilla2](https://user-images.githubusercontent.com/80963908/112749634-e64af980-8fc3-11eb-8b48-78f6d550b79c.png)

[NOTE:] Sometimes the light fixes itself is some entities are around it. [Screenshot 2] it fixed near the glow squids this time but it’s not always the case

Starlight :

![light](https://user-images.githubusercontent.com/80963908/112749643-ecd97100-8fc3-11eb-8936-148d9d1da884.png)

[EDIT: Updated the screenshots to look like they are supposed to]

**Comment by Spottedleaf** [comment]
Looks like https://github.com/Spottedleaf/Starlight/issues/25

**Comment by Spottedleaf** [comment]
1.0.0-RC1 has some fixes in the suspected area, can you re-test?

**Comment by toficzko** [comment]
I re-tested it now 

These are the results on a vanilla client with starlight for 21w11a from releases on the server:

![issue](https://user-images.githubusercontent.com/80963908/112748818-ae8d8300-8fbe-11eb-887a-d2191c28244f.png)

These are the results on a fabric client with the same version of starlight , as on the server:


![light](https://user-images.githubusercontent.com/80963908/112748865-00360d80-8fbf-11eb-85d4-69930f8b4f3c.png)

The results sadly are the same

[ I forgot to mention that the mobs spawn there because of the lightning in the issue description]

**Comment by toficzko** [comment]
And when switching back to vanilla on the server, the chunks get relighted and look like they are supposed to, with proper light


~~And the screenshots in the issue description , are very brightened up and i don't know why, but the other screenshots are ok , i need to update them~~

[EDIT: Updated]

**Comment by Spottedleaf** [comment]
This is certainly very odd. I produced it locally and will check it out.

I'm very unsure about why this is happening on the dedicated server and not the integrated; all of my 1.17 testing has been on integrated and I never saw any of it but my first dedicated test showed it.

**Comment by Spottedleaf** [comment]
This does not occur in 1.16.5.

**Comment by Spottedleaf** [comment]
I see where the problem is. The block light recalculation is incorrect in 1.17, as it's not using an offset.
Given it's a snapshot build, I'll simply update the artifact in the release page.

**Comment by Spottedleaf** [comment]
Update to the new version on the release page to fix

**Comment by toficzko** [comment]
I already Compiled the latest commit myself and the light issues are fixed , thanks
