### ISSUE TITLE
does not respect SemVer warning

### ISSUE THREAD

**Issue by TheDGOfficial** [Spottedleaf/Starlight#42]
```
Mod `starlight` (fabric-1.0.0-RC1-59d1f21) does not respect SemVer - comparison support is limited.
```

Though having commit hash, fabric/forge and such in the version string is good, it causes the above warning. Not sure if RC1 should be removed too to fix it, but it should support it. I'll assume it will be fixed once the 1.0 release is finalized?

**Comment by Spottedleaf** [comment]
People are going to build jars from commit hashes one way or another. I need to know when inspecting logs what version it is exactly.

**Comment by FranKusmiruk** [comment]
I mean, you could also follow semver instead, it'd be something like `1.0.0-RC1.fabric+59d1f21`

**Comment by Spottedleaf** [comment]
ill look into it for RC2
