### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by MineAndDine96** [Spottedleaf/Starlight#43]
If I load my game with starlight-fabric after a few seconds after joining a server it says "Saving World" and the game crashes. I loaded a few other mods, so I dont know if its maybe just an incompatibility with another mod. I hope this helps, here is the crash report. https://paste.ee/p/Bu0Dr

**Comment by K0-RR** [comment]
I'm just a random user but for me, it looks like the crash is caused by Sodium mod. Can you try loading the game without it?

**Comment by MineAndDine96** [comment]
I think it wasnt an actualy problem with that mod. I just have a really bad computer and from what I cant tell so far it only happens, when my computer reaches its complete hardware memory limit, because I set it too high in the comments. Maybe sodium closes the game safely, when it runs out of memory.

**Comment by Spottedleaf** [comment]
Update sodium https://github.com/CaffeineMC/sodium-fabric/issues/587

**Comment by MineAndDine96** [comment]
I am using the newest Sodium version. 0.1.0.

**Comment by K0-RR** [comment]
You are using the stable release which is very outdated. (They really should already release an update long time ago, so much bugs fixed...). Download Sodium/Next from GitHub actions like @Spottedleaf requested you to.

**Comment by MineAndDine96** [comment]
Ohh. My bad, I am dumb. I ment I use the 0.1.1 version from GitHub. I am sorry. Or is there an even newer versipn I dont know about? According to the sodium gradle.properties 0.1.1 is the newest version.
