### ISSUE TITLE
Black Blocks appearing when breaking blocks

### ISSUE THREAD

**Issue by Nebula240** [Spottedleaf/Starlight#46]
Im using starlight-forge-1.0.0-RC1-1.16.5.jar

When breaking blocks this black blocks would appear for half a sec, it's really weird and kinda annoying.
![2021-04-12_11 10 45](https://user-images.githubusercontent.com/62150697/114418330-69ea1600-9b80-11eb-8da8-9fe21d290f65.png)

**Comment by ChiefArug** [comment]
Most likely a mod conflict, can you provide a modlist for the devs?

**Comment by Spottedleaf** [comment]
I tested locally, by recording and inspecting frame-by-frame, and could not produce this issue. Could you provide a mod list, and perhaps test other blocks (like grass)?

**Comment by Spottedleaf** [comment]
No timely response
