### ISSUE TITLE
Lazy load vanilla lighting

### ISSUE THREAD

**Issue by Madis0** [Spottedleaf/Starlight#50]
> It needs to store whether a skylight data section is uninitialised or absent (Vanilla conflates the two) and Starlight does not propagate light into chunks not marked as lit. However, in modifying the data stored, it also marks the chunk as "unlit." and add its own special tag for whether the chunk is it. To Vanilla the data will look like the chunk needs lighting, and to Starlight it will look "lit." 

Reading this gave me an idea - what if Starlight loaded the world's lighting to its special tags, but also used the vanilla lighting engine in the background for compatibility? Obviously ignoring the vanilla data while Starlight is active, though.
That could improve the UX a lot in the case Starlight is disabled for any reason (outdated mod, incompatibilities, snapshots, etc.)

**Comment by Spottedleaf** [comment]
This seems too difficult to implement and correctly maintain, especially considering things like how load/save hooks are currently implemented in Minecraft. One light engine is scary enough.
