### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by srnyx** [Spottedleaf/Starlight#51]
Whenever I try to build from source I get this error: https://paste.srnyx.xyz/uvodomujiz.yaml

**Comment by Octol1ttle** [comment]
Make sure Git is installed and is functioning properly

**Comment by srnyx** [comment]
> Make sure Git is installed and is functioning properly

It is. I'm able to build other mods from their source.

**Comment by Spottedleaf** [comment]
Please use `git clone` when getting Starlight - I force builds to attach the current commit number so I can tell when people have built non-release commits.
