### ISSUE TITLE
Missing chunk emptiness map entries

### ISSUE THREAD

**Issue by UltraBlackLinux** [Spottedleaf/Starlight#56]
Hey there,
I just crashed, while joining a server, here are the logs:
https://paste.ee/p/eMRC5
Is that some mod incompatibility again?
Thanks!

**Comment by Spottedleaf** [comment]
This is probably a result of a mod conflict. Typically when chunks are loaded into the client the code is supposed to make calls to let the light engine know that a bunch of chunk sections have been loaded in, and it will say which ones are empty and which ones aren't. This crash will happen if not all chunk sections are accounted for in that logic.

I've set the chunk load hook for starlight to be immediately after that logic should run. So it's probably a mod loading in chunk data without calling the correct light engine logic.

**Comment by Spottedleaf** [comment]
So for RC3 I'm just going to write in some logic to simply init the emptiness maps instead of crashing.

**Comment by Spottedleaf** [comment]
Fixed in 1.0.0-RC3
