### ISSUE TITLE
[CRASH] java.lang.IllegalStateException: Current chunk has not initialised emptiness map yet supplied emptiness map isn't filled?

### ISSUE THREAD

**Issue by Redo11** [Spottedleaf/Starlight#64]
IDK what happened, I went AFK after playing on Hypixel, and it crashed. As I said, I was AFK, so no clue what could initiate that.
https://paste.atlauncher.com/view/bcd7da65-e804-4dad-8060-a954c4d84104

**Comment by Spottedleaf** [comment]
Duplicate of https://github.com/Tuinity/Starlight/issues/56
