### ISSUE TITLE
[REQUEST] Adding Starlight to mod distribution site(s)

### ISSUE THREAD

**Issue by Redo11** [Spottedleaf/Starlight#65]
You could add your mod to a site like Modrinth or Curseforge to increase user base.

I know, right now it is in BETA, but the mod is stable *enough* for daily use and there is nothing really stopping you from uploading it there.

I can understand, if you would prefer to delay it for release, just please consider it.

**Comment by solonovamax** [comment]
One of the reasons they might not want to add it, is because that encourages people to think it will "just work", whereas this is more of a "for developers only" type of thing until it's finished.

**Comment by piemanau** [comment]
They could just add [BETA] in the name or something like that though

**Comment by ghost** [comment]
Yes, the dev could just label that it's in an alpha/beta state.

**Comment by Spottedleaf** [comment]
This is being done now.
