### ISSUE TITLE
1.17 Massive Lag Spikes on Lighting Update (Happens with vanilla too but is improved by starlight)

### ISSUE THREAD

**Issue by PhantomG27249** [Spottedleaf/Starlight#66]
Happens when either placing or if using a dynamic lights mod that triggers actual lighting updates like lambdynamiclights. The results in a rendering lag spike on client. Starlight seems to improve it but it over vanilla but it is still very bad.

To reproduce
1. Boot up world
2. Place light source
3. Observe the lag graph while you place the light sources.

**Comment by Spottedleaf** [comment]
without any kind of profiling data I'm not even looking at this, I know for a fact starlight is fast. and I know you personally, you don't bother to do any kind of research, so until you do some pointing to starlight this will remain closed

**Comment by PhantomG27249** [comment]
What would you like me to profile specifically? It happens for a instant when placing the lighting source then goes away.  I said it seemed to be related to something on vanillas end and that starlight reduced but didn't eliminate it. Which is why I made the issue report as I had hoped on further investigation starlight might find another issue with mojangs code to fix and further speed up the game. It would also be good to verify that the issue isn't unique to my system.

**Comment by Spottedleaf** [comment]
You would use this to verify the cost of the light update https://github.com/Spottedleaf/lightbench

**Comment by PhantomG27249** [comment]
The issue seems to be unique to 1.17, is there a lightbench 1.17 version?
Edit: Let me verify the issue still happens on rc3 aswell and it wasn't already fixed.
Edit 2: Seems further reduced on rc3 to a point I don't think it matters (not perceptible without usage of frame time capture tools so whatever I was experiencing seems to be gone now as of rc3), if possible though I would still like to test with light bench on 1.17
