### ISSUE TITLE
[REQUEST] Make people able to download Starlight as a .jar

### ISSUE THREAD

**Issue by MagicJinn** [Spottedleaf/Starlight#69]
Please make people able to download this as a JAR file. I want to be able to use this mod but the lack of tutorials and my lack of understanding of how this works just makes me unable to. I downloaded every file, read all the text files and inspected every folder but I truly have no clue where to start...

**Comment by Octol1ttle** [comment]
Go to https://github.com/Spottedleaf/Starlight/releases, scroll down a bit, click on Assets, and download the appropriate JAR for your mod loader and Minecraft version

**Comment by MagicJinn** [comment]
Man that was hidden really well. It doesn't even have a proper button, it's just plain text. I recommend putting this link in the description of the mod, otherwise people won't really be able to find it.

**Comment by AndreVallestero** [comment]
> Man that was hidden really well. It doesn't even have a proper button, it's just plain text.

This is the [standard way](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github) to download things from GitHub, I would hardly call it hidden. In fact, mods like Sodium and Tinkers Construct also release their jars on GitHub this way:

- https://github.com/SlimeKnights/TinkersConstruct/releases
- https://github.com/CaffeineMC/sodium-fabric/releases
