### ISSUE TITLE
Crash when creating a schematic with litematic

### ISSUE THREAD

**Issue by Zailer43** [Spottedleaf/Starlight#7]
### Expected Behavior
I hope minecraft doesn't introduce any bugs when putting the 2 mods together

### Actual Behavior
When you load a schematic it crashes
[crash-2020-12-08_20.01.52-client.txt](https://github.com/Spottedleaf/Starlight/files/5662602/crash-2020-12-08_20.01.52-client.txt)

### Reproduction Steps
1. Press the M, Area selection browser, New selection, Name it and accept
![2020-12-08_20 00 41](https://user-images.githubusercontent.com/63565983/101555075-a3263580-3996-11eb-8dc3-4d99963c02db.png)

2. Make the selection with the tool (default is a stick)
![2020-12-08_20 00 50](https://user-images.githubusercontent.com/63565983/101555260-09ab5380-3997-11eb-95e8-eb0a35b6d846.png)

3, Press the M, Area selection browser, Configure, Save schematic, Save schematic
4. Press the M, Load schematics, click on the schematic created
![2020-12-08_20 01 46](https://user-images.githubusercontent.com/63565983/101555523-9a822f00-3997-11eb-89ff-b89bb8331757.png)

**Comment by Spottedleaf** [comment]
I have this probably fixed locally, I'll push when I've refactored the skylight nibble management.

**Comment by GaiaB0t** [comment]
for me it was happening whenever anything visual was loaded in litematica
