### ISSUE TITLE
Fabric 1.17 chunk borders causing lighting issues

### ISSUE THREAD

**Issue by DVIcable** [Spottedleaf/Starlight#71]
Starlight 1.17.x RC2 is the only mod installed

Placing more than one light source with the /fill command fails to emit light across borders
![2021-06-26_14 07 10](https://user-images.githubusercontent.com/76571917/123525008-34d36700-d68b-11eb-82c6-38d05e1c5bc2.png)
![2021-06-26_14 07 24](https://user-images.githubusercontent.com/76571917/123525012-3a30b180-d68b-11eb-99c2-2fb9ad952cf5.png)

Block updates allow neighbouring blocks to light the surrounding area properly
![2021-06-26_13 32 10](https://user-images.githubusercontent.com/76571917/123525111-cf33aa80-d68b-11eb-928c-e333042bcc3e.png)
![2021-06-26_13 32 34](https://user-images.githubusercontent.com/76571917/123525114-d1960480-d68b-11eb-8bff-7f4728d9872b.png)

Fire is a weird one
![2021-06-26_13 07 04](https://user-images.githubusercontent.com/76571917/123525179-17eb6380-d68c-11eb-872b-01ed11f07c46.png)
The natural fire decay updates surrounding fire blocks and allows them to work properly
![2021-06-26_13 07 25](https://user-images.githubusercontent.com/76571917/123525181-1a4dbd80-d68c-11eb-8044-530cf81e1872.png)
However this process leaves lingering light around the borders
![2021-06-26_13 06 43](https://user-images.githubusercontent.com/76571917/123525184-1c178100-d68c-11eb-96cd-386490ac9900.png)

**Comment by Spottedleaf** [comment]
can produce; looks like a problem with specifically chunk edges. so relogging will fix it, but i'll fix this next commit

**Comment by Spottedleaf** [comment]
produced the massive fill on vanilla

**Comment by Spottedleaf** [comment]
uh yeah this is actually a vanilla problem that occurs when you do massive /fill

**Comment by Spottedleaf** [comment]
Fixed in 1.0.0-RC3
