### ISSUE TITLE
Gradle spams "unknown invokedynamic bsm" when building.

### ISSUE THREAD

**Issue by K0-RR** [Spottedleaf/Starlight#74]
This gets printed over 3000 times when building from source.
`unknown invokedynamic bsm: java/lang/invoke/StringConcatFactory/makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite; (tag=6 iif=false)`

**Comment by jpenilla** [comment]
The issue here is loom using an outdated version of tiny-remapper. Not a Starlight issue, will be resolved when leaf decides to update to loom 0.9+.
