### ISSUE TITLE
Starlight 1.0.0-RC3 Client Stall

### ISSUE THREAD

**Issue by sxphirus** [Spottedleaf/Starlight#77]
### **What is it?**

Client stall issue with sculk sensors (possibly even an issue on servers running Tuinity & downstream)

### **Reproduction Steps**

1. Use the latest starlight release (1.0.0-RC3) standalone w/ fabric (1.17.1).
2. Place down a square (5x5 worked for me) of sculk sensors with redstone lamps on top
3. Activate them by walking around, the client will stall for 1-2 minutes

**Comment by sxphirus** [comment]
I just thought I'd add I've tested this without starlight on both bare fabric and vanilla installs and this is not an issue

**Comment by ghost** [comment]
can confirm it makes mega lag, even with a single lantern, look at this clientside spark report: https://imgur.com/a/QiGkIsU

**Comment by Spottedleaf** [comment]
Oh wow, the VoxelShape checking logic is really bad. I have fixes for that in Tuinity but I'm not sure about how to port those over. 
If you can provide me the world you used to create that, and the version of the game you are on I can take a look for myself and confirm it

**Comment by sxphirus** [comment]
[starlight fresh test.zip](https://github.com/Tuinity/Starlight/files/6855298/starlight.fresh.test.zip)
sorry for the slow response, this is my test world for you @Spottedleaf 
loaded on 1.17.1 w/ starlight 1.0.0-rc3

i recommend u just load it with **vanilla first** or else your client will crash, I cant even get into the world with starlight anymore without 1-2 minute freezes every 10 seconds

co-ords for the thing are -80 8 -50

**Comment by xanderstuff** [comment]
I can confirm I have the same issue. `Minecraft 1.17 + fabric` (not 1.17.1) with `starlight 1.0.0-RC3+fabric.`2b7d7ae. I am using other mods as well.

On a singleplayer world, I just made a flat 5x5 grid of skulk sensors and placed a redstone lamp on top. The redstone lamp turns on easily, but when turning off, it freezes my client for about 30 seconds. The integrated server seems unaffected.
Using a smaller, 3x3 skulk grid, the rendering thread freezes for about 2 seconds, so I recommend using a smaller amount of skulk sensors for testing. Placing or removing a torch near the skulk sensors also freezes the client.

Server thread spark, placing a redstone lamp above a grid of skulk sensors: https://spark.lucko.me/qCkeewIRGc
Rendering thread spark, placing a redstone lamp above a grid of skulk sensors: : https://spark.lucko.me/SpIlS5Tpps

**Comment by xanderstuff** [comment]
It may be worth noting a skulk sensor gives off a block light level of 1 [source: minecraft wiki](https://minecraft.fandom.com/wiki/Sculk_Sensor)

**Comment by Spottedleaf** [comment]
Thanks, I can produce this locally now
- Doesn't happen on vanilla

**Comment by Spottedleaf** [comment]
This is fixed by https://github.com/PaperMC/Starlight/commit/5e53c1f7afcb1eb2e7a5471919c5c42d2b55c46f, I'm not pushing a build yet as I want to verify if it fixes another issue first

**Comment by Spottedleaf** [comment]
This is now fixed in 1.0.0. You can get that from CurseForge when it's been published.
