### ISSUE TITLE
Incompatibility with LambdaBetterGrass + Sodium + Indium

### ISSUE THREAD

**Issue by solarft** [Spottedleaf/Starlight#78]
![image](https://user-images.githubusercontent.com/49528667/126055785-27e87a5b-c773-440e-a218-cef0822422b0.png)
4 Mods:
Sodium
Indium
LambdaBetterGrass
Fabric API

When all of these mods are combined, this happens. Its xray ngl

**Comment by craftycorvid** [comment]
I'm running those 4 mods and not seeing this. Make sure you're running the latest version of Indium.

**Comment by tjhooker73ps3** [comment]
Its LambdaBetterGrass. Its incompatible with Sodium 0.3.0 Same thing happens with connected-block-textures-0.1.51.17 and sodium 0.3.0 Use Iris their version of sodium works with these mods.

**Comment by solarft** [comment]
Yep, just updated my Indium, and its not xray anymore. yay. Maybe its time I should try iris.

**Comment by MaxBr5** [comment]
Useful if you want to find diamonds and cheat ☻

**Comment by teppyboy** [comment]
If the problem is solved then close the issue I guess

**Comment by DioEgizio** [comment]
Why is this issue still open?
