### ISSUE TITLE
[fabric] incompatibility with Iris

### ISSUE THREAD

**Issue by MaxBr5** [Spottedleaf/Starlight#79]
<pre>When I full screen with Starlight and a good shaders
and entity optimization mod called Iris, it crashes in a manner
that no logs are created and the screen turns black, yet
everything else runs fine including the Minecraft music,
pigs and Elisia the little block hen, even a web server or
a Minecraft server would run perfectly fine.</pre>

**Comment by Kichura** [comment]
![mc](https://user-images.githubusercontent.com/68134602/127741592-fbf41d28-4b3a-4754-b6e2-613f4810f152.png)

Cannot reproduce on GTX 1650 via Prismarine Shaders. (Are your mods up-to-date? + What drivers are you using?)

**Comment by MaxBr5** [comment]
I use intel integrated graphics on windows.

**Comment by MaxBr5** [comment]
And I don't use sodium for I hate the sodium video settings menu

**Comment by K0-RR** [comment]
@Kichura I tried Iris + Starlight + Prismarine Shaders with GTX 1070 (460.91.03) and all I got is this 95% opaque white screen seen above
![2021-07-31_23 08 35](https://user-images.githubusercontent.com/43277609/127752487-3d2409ab-9851-4eee-ab1b-bd30c5cba92d.png)
Did you make any changes to the config?

**Comment by Kichura** [comment]
> 
> 
> @Kichura I tried Iris + Starlight + Prismarine Shaders with GTX 1070 (460.91.03) and all I got is this 95% opaque white screen seen above
> ![2021-07-31_23 08 35](https://user-images.githubusercontent.com/43277609/127752487-3d2409ab-9851-4eee-ab1b-bd30c5cba92d.png)
> Did you make any changes to the config?

I disabled clouds via the settings file as that's what the shader author told me to do. (see libs/settings.glsl -> #define clouds)

**Comment by Kichura** [comment]
> 
> 
> I use intel integrated graphics on windows.

Update your driver if you can and try running mc with just starlight in case. + Does the black fullscreen apply to other shaders or any even without?

**Comment by MaxBr5** [comment]
<pre>I use skylec and complimentary shaders, both
don't work but I do have clouds turned on.</pre>

**Comment by AlsoSylv** [comment]
Unless this is a custom compile or a fork they are also using sodium, but a list of mods would help

**Comment by Genau6502** [comment]
I cannot confirm this issue on intel/windows with the same shaderpack listed

**Comment by DioEgizio** [comment]
> And I don't use sodium for I hate the sodium video settings menu

Press shift p on video settings and there you can use vanilla video settings lol

**Comment by NotADinosaur** [comment]
> Press shift p on video settings and there you can use vanilla video settings lol

Really? If that works, then **THANK YOU**.
