### ISSUE TITLE
[Fabric] conflict with phosphor

### ISSUE THREAD

**Issue by Anonym3310** [Spottedleaf/Starlight#81]
[18:27:37] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: phosphor conflicts with {starlight @ [*]}
[latest.log](https://github.com/Tuinity/Starlight/files/6887915/latest.log)

**Comment by Octol1ttle** [comment]
This is to be expected, as Starlight and Phosphor modify the same part of the game - the lighting engine. Please remove Phosphor, and no crash should occur

**Comment by Roan-V** [comment]
Phosphor makes enhancements to the slow vanilla lighting engine to make it faster.
Starlight completely rips out the vanilla lighting engine and replaces it with a completely new even faster system.

Surprised that they don't work together?

**Comment by Anonym3310** [comment]
I see, thanks for the explanation
