### ISSUE TITLE
Performance drop on my world

### ISSUE THREAD

**Issue by Ivan-Khar** [Spottedleaf/Starlight#82]
I am currently making a parkour map with extended height. Everything works fine until I go up to -320 -- -290 height.
My fps drops from 60 to 10-20. And I don't know why.

[Map download link](https://drive.google.com/file/d/1pz4NJSd4nTLNgKLQsQzcak8YDDE2XSgK/view?usp=sharing)

**Comment by Spottedleaf** [comment]
The client renderer doesn't take kindly to world height. Have you actually ruled out starlight?

**Comment by Ivan-Khar** [comment]
Uhh yes, without starlight it's working smoothly

**Comment by Amaroq-Clearwater** [comment]
Maybe record some video and grab some logs. Also share a list of all of the mods you're running.

**Comment by AquUpd** [comment]
Weird, but can't reproduce it too.

**Comment by AquUpd** [comment]
Oh, i think that some of my mod is doing this, but not sure what mod
![image](https://user-images.githubusercontent.com/47220198/132239019-35175aa6-2e31-4a00-8755-e9afdf3dc940.png)

**Comment by Ivan-Khar** [comment]
With Sodium + Starlight + lazyDFU only it's working pretty well

**Comment by Ivan-Khar** [comment]
Current modlist:
![Mods](https://user-images.githubusercontent.com/47220198/132240247-456ae8aa-900e-4031-91a6-f50f47245cec.png)

Video:
https://user-images.githubusercontent.com/47220198/132240281-738a9e8b-657a-4d05-ba9f-bded9f768258.mp4

Latest.log:
[latest.log](https://github.com/PaperMC/Starlight/files/7116922/latest.log)

**Comment by Ivan-Khar** [comment]
Same mods without starlight:
https://user-images.githubusercontent.com/47220198/132240940-734101db-daae-4f57-a528-0d546c429702.mp4

**Comment by Amaroq-Clearwater** [comment]
Yikes! o.o

**Comment by RealCamar** [comment]
> Current modlist:
> 
> ![Mods](https://user-images.githubusercontent.com/47220198/132240247-456ae8aa-900e-4031-91a6-f50f47245cec.png)
> 
> 
> 
> Video:
> 
> https://user-images.githubusercontent.com/47220198/132240281-738a9e8b-657a-4d05-ba9f-bded9f768258.mp4
> 
> 
> 
> Latest.log:
> 
> [latest.log](https://github.com/PaperMC/Starlight/files/7116922/latest.log)
> 
> 
> 
> 

It seems like you're not using the latest version if Starlight. Get the latest build [here](https://modrinth.com/mod/starlight)

**Comment by RealCamar** [comment]
Not sure if it would solve your issue though.

**Comment by Ivan-Khar** [comment]
> 
> 
> > Current modlist:
> > ![Mods](https://user-images.githubusercontent.com/47220198/132240247-456ae8aa-900e-4031-91a6-f50f47245cec.png)
> > Video:
> > 
> >   
> >     
> >     
> > 
> >     2021-09-06.18-38-15.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > Latest.log:
> > [latest.log](https://github.com/PaperMC/Starlight/files/7116922/latest.log)
> 
> It seems like you're not using the latest version if Starlight. Get the latest build [here](https://modrinth.com/mod/starlight)

I already have latest version of startlight from here https://github.com/PaperMC/Starlight/releases

**Comment by Ivan-Khar** [comment]
And yeah, fps drops even with latest version from modrinth

**Comment by Kichura** [comment]
Cannot reproduce with latest compiled starlight for 1.17.x, even with every mod updated that i could find; Perhaps some hardware issue that causes FPS drops or something beyond that?

**Comment by Spottedleaf** [comment]
I need client sparks to figure this out, unfortunately. https://www.curseforge.com/minecraft/mc-mods/spark
