### ISSUE TITLE
RGB light channels

### ISSUE THREAD

**Issue by ZenithRogue** [Spottedleaf/Starlight#94]
I fully understand this is probably out of scope for the project, so this this is more of a question of curiosity.

How capable would this engine be at transforming the lighting into a 4 channel RGB+Intensity setup?

A compatible client mod would obviously have to be made, along with an index of light emitting blocks and their corresponding colors.

**Comment by Spottedleaf** [comment]
I have no idea how it would work, the intensity part is the trouble. 

At that point you might as well just use standard lighting that games have seemed to have figured out over the past decade or so.

**Comment by Khodyn** [comment]
Not sure why intensity is necessary?
