### ISSUE TITLE
[Fabric] Mod Incompatibility with Kibe - Breaks Big Torch functionality 

### ISSUE THREAD

**Issue by dandin87** [Spottedleaf/Starlight#95]
Kibe has an a tile-entity called the Big Torch. You can place torches inside of this big torch in stacks which disables hostile mob spawns in a radius up to 8 chunks. At one point this did work with Starlight but I know it broke with at least RC3 but probably before that as I know its also broken with 1.16. The Big Torch basically returns 15 light level during spawn checking. Perhaps there is a more compatible way for them to change this behavior with Starlight? 
https://github.com/lucaargolo/kibe/issues/77
https://github.com/lucaargolo/kibe/blob/1.17/src/main/java/io/github/lucaargolo/kibe/mixin/LightStorageMixin.java

So far this is the only mod incompatibility I know of for Fabric. We have been using Starlight on the public All of Fabric 3 servers since December 2020 and All of Fabric 4 since we released the pack. Amazing work. We recommend Starlight all the time.

**Comment by Spottedleaf** [comment]
Looks like it was fixed on their end
