### ISSUE TITLE
Starlight "breaks" existing light-suppressed areas

### ISSUE THREAD

**Issue by ghost** [Spottedleaf/Starlight#96]
This may be considered as intended, but starlight seems to "break" existing light-suppressed areas.
Normally, these should only break if the light gets updated, I am bringing this up because phosphor doesn't seem to affect that.

**How to reproduce :**

- Open minecraft _without_ starlight
- Reproduce this bug : https://bugs.mojang.com/browse/MC-164281
- Close the game
- Open minecraft _with_ phosphor
- Reopen the world (the light-suppressed area should still "work")
- Close the game
- Open minecraft _with_ starlight
- Reopen the world

Here is an experimental 1.17.1 phosphor commit (thanks to PhiPro for sharing it) if you want to test it yourself (the official release is not available at the time of writing this report) : https://www.mediafire.com/file/mirofxwqnekax0o/phosphor-fabric-mc1.17.1-0.7.2build.180.jar/file

**Comment by MWHunter** [comment]
Phosphor isn’t a rewrite while Starlight is, which explains the difference

**Comment by jpenilla** [comment]
> This may be considered as intended

You are correct, fixing bugs like light supression is a goal of Starlight, fixing this "issue" (unfixing this bug) isn't something the team is interested in.
